<#
.SYNOPSIS
    SharePoint Permission Scanner - Generates a detailed HTML report of all permissions
    across SharePoint sites, libraries, folders, and files.

.DESCRIPTION
    This script connects to SharePoint Online using PnP PowerShell and recursively
    scans permissions at all levels: Site, Lists/Libraries, Folders, and Files.
    It detects broken inheritance and exports a rich interactive HTML report.

.PARAMETER Mode
    Scanning mode:
      - SingleSite     : Scan a single SharePoint site
      - AllSites       : Scan all sites in the tenant
      - SiteCollection : Scan a specific site collection (root + subsites)

.PARAMETER SiteUrl
    URL of the SharePoint site (required for SingleSite and SiteCollection modes).

.PARAMETER TenantAdminUrl
    URL of the SharePoint Admin Center (e.g. https://contoso-admin.sharepoint.com).
    Required for AllSites mode.

.PARAMETER OutputPath
    Path and filename for the HTML report. Defaults to .\SPPermissions_<timestamp>.html

.PARAMETER IncludeFiles
    If set, scans individual file permissions (slower but more thorough). Default: $true

.PARAMETER MaxFileDepth
    Maximum folder depth to scan for files. Default: 10

.PARAMETER ExcludeSystemLists
    Exclude SharePoint system lists (Style Library, Site Assets, etc.). Default: $true

.PARAMETER ClientId
    Azure AD App Registration Client ID for app-only authentication.

.PARAMETER Thumbprint
    Certificate thumbprint for app-only authentication.

.PARAMETER Tenant
    Tenant ID or domain for app-only authentication.

.EXAMPLE
    # Interactive login - Single site
    .\SPPermissionScanner.ps1 -Mode SingleSite -SiteUrl "https://contoso.sharepoint.com/sites/HR"

.EXAMPLE
    # All sites in tenant
    .\SPPermissionScanner.ps1 -Mode AllSites -TenantAdminUrl "https://contoso-admin.sharepoint.com"

.EXAMPLE
    # App-only auth - Site collection
    .\SPPermissionScanner.ps1 -Mode SiteCollection -SiteUrl "https://contoso.sharepoint.com/sites/Projects" `
        -ClientId "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" `
        -Thumbprint "ABCDEF1234567890" `
        -Tenant "contoso.onmicrosoft.com"

.NOTES
    Author  : Generated by Claude
    Version : 1.0
    Requires: PnP.PowerShell module (Install-Module PnP.PowerShell)
    
    Required permissions (App-only):
      - Sites.FullControl.All (SharePoint)
      - Directory.Read.All (Graph - for user/group details)
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [ValidateSet("SingleSite", "AllSites", "SiteCollection")]
    [string]$Mode,

    [Parameter()]
    [string]$SiteUrl,

    [Parameter()]
    [string]$TenantAdminUrl,

    [Parameter()]
    [string]$OutputPath = ".\SPPermissions_$(Get-Date -Format 'yyyyMMdd_HHmmss').html",

    [Parameter()]
    [ValidateSet("Site", "SiteAndLibraries", "Full")]
    [string]$ScanDepth = "SiteAndLibraries",
    # Site              : Site uniquement (permissions du site)
    # SiteAndLibraries  : Site + Listes/Bibliotheques (recommande, rapide)
    # Full              : Site + Bibliotheques + Dossiers + Fichiers (lent)

    [Parameter()]
    [bool]$ExcludeSystemLists = $true,

    [Parameter()]
    [string]$ClientId,

    [Parameter()]
    [string]$Thumbprint,


    [Parameter()]
    [string]$ClientSecret,
    # Alternative au certificat : client secret Azure AD
    [Parameter()]
    [string]$Tenant,

    [Parameter()]
    [string]$FocusUser,
    # Filtrer par utilisateur/groupe : ne retourne que les objets ou ce principal a acces
    # Ex: -FocusUser "john.doe@contoso.com"

    [Parameter()]
    [string]$CompareWith,
    # CSV d un scan precedent pour comparaison avant/apres
    # Ex: -CompareWith ".\SPPermissions_20260501.csv"

    [Parameter()]
    [switch]$IncludeOneDrive,
    # Inclure les sites OneDrive personnels (mode AllSites uniquement)

    [Parameter()]
    [switch]$Resume,
    # Reprendre un scan interrompu (mode AllSites) depuis le dernier checkpoint

    [Parameter()]
    [int]$MaxRetries = 5
    # Nombre de tentatives en cas de throttling SharePoint (429)
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

#region ──────────────────────── GLOBALS ────────────────────────

$Script:ScanResults   = [System.Collections.Generic.List[PSCustomObject]]::new()
$Script:ScanErrors    = [System.Collections.Generic.List[PSCustomObject]]::new()
$Script:TotalScanned  = 0
$Script:GroupMembers  = [System.Collections.Generic.Dictionary[string,object]]::new()
$Script:StartTime     = Get-Date
$Script:CurrentSiteGroupId = $null  # GroupId M365 du site en cours (Team-connected site)
$Script:CurrentOwnerGroupId  = $null  # Id du groupe SP "Owners" du site en cours
$Script:CurrentMemberGroupId = $null  # Id du groupe SP "Members" du site en cours
$Script:CurrentVisitorGroupId= $null  # Id du groupe SP "Visitors" du site en cours

# ── Resilience (gros scans) ──
$Script:CsvStreamPath   = $null   # CSV ecrit au fil de l eau
$Script:CsvHeaderWritten= $false  # En-tete CSV deja ecrit ?
$Script:CheckpointPath  = $null   # Liste des sites deja scannes
$Script:CompletedSites  = [System.Collections.Generic.HashSet[string]]::new()
$Script:LastReconnect   = Get-Date # Pour reconnexion periodique du token
$Script:SystemLists   = @(
    "appdata", "appfiles", "composed looks", "converted forms",
    "form templates", "list template gallery", "master page gallery",
    "preservation hold library", "site collection images",
    "site pages", "solution gallery", "style library",
    "theme gallery", "user information list", "web part gallery",
    "site assets", "cache profiles", "content and structure reports",
    "content type publishing error log", "customized reports",
    "designated sites", "devices", "hold reports", "relationships list",
    "reusable content", "suggested content browser locations",
    "taxonomy hidden list", "translation status", "wfpub", "wfsvc"
)

#endregion

#region ──────────────────────── HELPERS ────────────────────────

function Write-Log {
    param([string]$Message, [string]$Level = "INFO")
    $timestamp = Get-Date -Format "HH:mm:ss"
    $color = switch ($Level) {
        "INFO"    { "Cyan" }
        "OK"      { "Green" }
        "WARN"    { "Yellow" }
        "ERROR"   { "Red" }
        "SECTION" { "Magenta" }
        default   { "White" }
    }
    Write-Host "[$timestamp] " -NoNewline -ForegroundColor DarkGray
    Write-Host "[$Level] " -NoNewline -ForegroundColor $color
    Write-Host $Message
}

function Add-Result {
    param(
        [string]$SiteUrl,
        [string]$SiteName,
        [string]$ObjectType,   # Site | Library | List | Folder | File
        [string]$ObjectName,
        [string]$ObjectUrl,
        [bool]$HasUniquePermissions,
        [string]$InheritedFrom,
        [PSCustomObject[]]$Permissions
    )
    $Script:ScanResults.Add([PSCustomObject]@{
        SiteUrl              = $SiteUrl
        SiteName             = $SiteName
        ObjectType           = $ObjectType
        ObjectName           = $ObjectName
        ObjectUrl            = $ObjectUrl
        HasUniquePermissions = $HasUniquePermissions
        InheritedFrom        = $InheritedFrom
        Permissions          = $Permissions
        ScannedAt            = (Get-Date -Format "o")
    })
    $Script:TotalScanned++
}



#endregion

#region ──────────────────────── CONNECT ────────────────────────

function Connect-ToSite {
    param([string]$Url)
    Write-Log "Connecting to: $Url" -Level INFO
    try {
        if ($ClientId -and $ClientSecret -and $Tenant) {
            # Authentification par Client Secret (pas de certificat requis)
            Write-Log "Auth: Client Secret" -Level INFO
            Connect-PnPOnline -Url $Url -ClientId $ClientId -ClientSecret $ClientSecret -Tenant $Tenant -ErrorAction Stop
        } elseif ($ClientId -and $Thumbprint -and $Tenant) {
            # Verify certificate exists in store
            $cert = Get-Item "Cert:\CurrentUser\My\$Thumbprint" -ErrorAction SilentlyContinue
            if (-not $cert) {
                $cert = Get-Item "Cert:\LocalMachine\My\$Thumbprint" -ErrorAction SilentlyContinue
            }
            if (-not $cert) {
                throw "Certificate with thumbprint '$Thumbprint' not found in CurrentUser\My or LocalMachine\My store. Import the .pfx file first: Import-PfxCertificate -FilePath '<path>.pfx' -CertStoreLocation Cert:\CurrentUser\My"
            }
            Write-Log "Certificate found: $($cert.Subject) (expires $($cert.NotAfter.ToString('yyyy-MM-dd')))" -Level OK
            # App-only auth with certificate thumbprint
            Connect-PnPOnline -Url $Url `
                -ClientId $ClientId `
                -Thumbprint $Thumbprint `
                -Tenant $Tenant `
                -ErrorAction Stop
        } elseif ($ClientId -and $Tenant) {
            # App-only auth - interactive device login
            Connect-PnPOnline -Url $Url `
                -ClientId $ClientId `
                -Tenant $Tenant `
                -Interactive `
                -ErrorAction Stop
        } else {
            # Delegated interactive login (uses PnP community app)
            Connect-PnPOnline -Url $Url -Interactive -ErrorAction Stop
        }
        Write-Log "Connected successfully." -Level OK
        $Script:LastReconnect = Get-Date
    } catch {
        Write-Log "Connection failed: $_" -Level ERROR
        throw
    }
}

#endregion

#region ──────────────────────── RESILIENCE (gros scans) ────────────────────────

function Invoke-WithRetry {
    <#
        Execute un scriptblock avec gestion du throttling SharePoint (429 / 503).
        Respecte l en-tete Retry-After si present, sinon backoff exponentiel.
    #>
    param(
        [scriptblock]$Action,
        [string]$Context = "operation"
    )
    $attempt = 0
    while ($true) {
        try {
            return & $Action
        } catch {
            $attempt++
            $msg = $_.Exception.Message
            $isThrottle = $msg -match '429|throttl|too many requests|503|Service Unavailable|temporarily'

            if (-not $isThrottle -or $attempt -ge $MaxRetries) {
                throw   # Erreur non-throttling OU trop de tentatives -> remonter
            }

            # Chercher un Retry-After dans l exception
            $wait = 0
            if ($_.Exception.Response -and $_.Exception.Response.Headers) {
                try {
                    $ra = $_.Exception.Response.Headers['Retry-After']
                    if ($ra) { $wait = [int]$ra }
                } catch {}
            }
            if ($wait -le 0) { $wait = [math]::Min(60, [math]::Pow(2, $attempt)) }  # backoff expo, max 60s

            Write-Log "Throttling detecte sur $Context (tentative $attempt/$MaxRetries) - pause ${wait}s" -Level WARN
            Start-Sleep -Seconds $wait
        }
    }
}

function Test-TokenRefresh {
    <#
        Reconnecte si le token approche de l expiration (>45 min depuis derniere connexion).
        Les tokens app-only SharePoint expirent generalement apres 1h.
    #>
    param([string]$Url)
    $elapsed = (Get-Date) - $Script:LastReconnect
    if ($elapsed.TotalMinutes -ge 45) {
        Write-Log "Reconnexion preventive du token (>45min)..." -Level INFO
        try {
            Connect-ToSite -Url $Url
        } catch {
            Write-Log "Reconnexion echouee, poursuite avec le token actuel : $_" -Level WARN
        }
    }
}

function Initialize-IncrementalSave {
    <#
        Prepare le CSV en ecriture au fil de l eau + le fichier checkpoint.
        En mode -Resume, charge la liste des sites deja scannes.
    #>
    param([string]$CsvPath)
    $Script:CsvStreamPath  = $CsvPath
    $Script:CheckpointPath = $CsvPath -replace '\.csv$', '.checkpoint'

    if ($Resume -and (Test-Path $Script:CheckpointPath)) {
        $done = Get-Content $Script:CheckpointPath -ErrorAction SilentlyContinue
        foreach ($s in $done) { if ($s.Trim()) { [void]$Script:CompletedSites.Add($s.Trim()) } }
        Write-Log "Reprise : $($Script:CompletedSites.Count) site(s) deja scanne(s) seront ignores" -Level INFO

        # Si le CSV existe deja, on garde son contenu (header deja ecrit)
        if (Test-Path $Script:CsvStreamPath) {
            $Script:CsvHeaderWritten = $true
            Write-Log "CSV existant conserve, ajout en mode append" -Level INFO
        }
    } else {
        # Nouveau scan : repartir de zero
        if (Test-Path $Script:CsvStreamPath)  { Remove-Item $Script:CsvStreamPath  -Force -ErrorAction SilentlyContinue }
        if (Test-Path $Script:CheckpointPath) { Remove-Item $Script:CheckpointPath -Force -ErrorAction SilentlyContinue }
        $Script:CsvHeaderWritten = $false
    }
}

function Save-SiteResults {
    <#
        Ecrit les resultats accumules pour un site dans le CSV (append) puis
        marque le site comme termine dans le checkpoint. Vide ensuite la memoire.
    #>
    param([string]$SiteUrl)

    if (-not $Script:CsvStreamPath) { return }

    # Convertir les resultats en lignes plates (meme logique que Export-CsvReport)
    $flatRows = ConvertTo-FlatRows -Results $Script:ScanResults

    if ($flatRows.Count -gt 0) {
        if (-not $Script:CsvHeaderWritten) {
            $flatRows | Export-Csv -Path $Script:CsvStreamPath -Encoding UTF8 -NoTypeInformation -Force
            $Script:CsvHeaderWritten = $true
        } else {
            $flatRows | Export-Csv -Path $Script:CsvStreamPath -Encoding UTF8 -NoTypeInformation -Append
        }
    }

    # Marquer le site comme termine
    Add-Content -Path $Script:CheckpointPath -Value $SiteUrl -Encoding UTF8
    [void]$Script:CompletedSites.Add($SiteUrl)

    # Liberer la memoire : on a deja persiste ces resultats
    $Script:ScanResults.Clear()
}

#endregion

#region ──────────────────────── SCAN FUNCTIONS ────────────────────────

function Invoke-ScanItem {
    param(
        [string]$SiteUrl,
        [string]$SiteName,
        [string]$ListTitle,
        [object]$Item,
        [string]$ParentName,
        [string]$ObjectType
    )
    try {
        $hasUnique = $Item.HasUniqueRoleAssignments
        $name = if ($Item.FieldValues["FileLeafRef"]) { $Item.FieldValues["FileLeafRef"] } else { $Item.FieldValues["Title"] }
        $ref  = $Item.FieldValues["FileRef"]
        $url  = if ($ref) { "$SiteUrl$ref" } else { $SiteUrl }

        # Charger les permissions uniquement si l item a des permissions uniques
        # Si herite, ses permissions = parent -> pas besoin de charger (et on ne devrait
        # pas arriver ici grace au filtrage dans Invoke-ScanList)
        $perms = if ($hasUnique) {
            Get-SPPermissions -SecurableObject $Item
        } else { @() }

        Add-Result -SiteUrl $SiteUrl -SiteName $SiteName `
            -ObjectType $ObjectType -ObjectName $name `
            -ObjectUrl $url `
            -HasUniquePermissions $hasUnique `
            -InheritedFrom $(if ($hasUnique) { [string]::Empty } else { $ParentName }) `
            -Permissions $perms

        $icon = if ($ObjectType -eq "Folder") { "F" } else { "D" }
        Write-Log "  [$icon] $ObjectType : $name | Unique: $hasUnique" -Level INFO
    } catch {
        $Script:ScanErrors.Add([PSCustomObject]@{ Item = "$ListTitle/$($Item.Id)"; Error = $_.ToString() })
        Write-Log "  Error scanning $ObjectType $($Item.Id): $_" -Level WARN
    }
}

function Invoke-ScanList {
    param(
        [string]$SiteUrl,
        [string]$SiteName,
        [object]$List
    )
    $listType = if ($List.BaseType -eq "DocumentLibrary") { "Library" } else { "List" }
    Write-Log "  📚 Scanning $listType : $($List.Title)" -Level INFO

    try {
        # Permissions de la liste/bibliotheque (toujours chargees, heritees ou uniques)
        $listFull  = Get-PnPList -Identity $List.Id -Includes HasUniqueRoleAssignments, RoleAssignments
        $hasUnique = $listFull.HasUniqueRoleAssignments

        # On charge toujours les permissions effectives (meme si heritees du site)
        $perms = Get-SPPermissions -SecurableObject $listFull

        Add-Result -SiteUrl $SiteUrl -SiteName $SiteName `
            -ObjectType $listType -ObjectName $List.Title `
            -ObjectUrl "$SiteUrl$($List.DefaultViewUrl)" `
            -HasUniquePermissions $hasUnique `
            -InheritedFrom $(if ($hasUnique) { [string]::Empty } else { $SiteName }) `
            -Permissions $perms

        # Scanner les items selon le ScanDepth
        if ($ScanDepth -eq "Full" -and $List.BaseType -eq "DocumentLibrary") {

            # IMPORTANT : meme si la bibliotheque herite du site, un fichier/dossier
            # a l interieur peut avoir des permissions uniques (partage individuel).
            # On interroge donc TOUJOURS les items via REST (1 appel par bibliotheque)
            # et on ne scanne en profondeur que ceux avec HasUniqueRoleAssignments=true.
            $listId   = $List.Id
            $restUrl  = "/_api/web/lists(guid'$listId')/items?" +
                        "`$select=Id,FileLeafRef,FileRef,FSObjType,HasUniqueRoleAssignments" +
                        "&`$top=5000"

            try {
                $restResult  = Invoke-PnPSPRestMethod -Url $restUrl -Method Get
                $allItems    = @($restResult.value)
                $uniqueItems = @($allItems | Where-Object { $_.HasUniqueRoleAssignments -eq $true })
            } catch {
                # Fallback : Get-PnPListItem sans HasUniqueRoleAssignments, puis check individuel
                Write-Log "    REST fallback: $_ - utilisation de Get-PnPListItem" -Level WARN
                $pnpItems    = @(Get-PnPListItem -List $List.Id `
                    -Fields "FileLeafRef","FileRef","FSObjType" -PageSize 500)
                $allItems    = $pnpItems
                # Charger HasUniqueRoleAssignments item par item (plus lent)
                $uniqueItems = @($pnpItems | Where-Object {
                    try {
                        Get-PnPProperty -ClientObject $_ -Property HasUniqueRoleAssignments | Out-Null
                        $_.HasUniqueRoleAssignments
                    } catch { $false }
                })
            }

            $totalItems = $allItems.Count
            Write-Log "    $totalItems items dans $($List.Title) - $($uniqueItems.Count) avec permissions uniques" -Level INFO

            if ($uniqueItems.Count -eq 0) {
                Write-Log "    [SKIP] Aucun item avec permissions uniques." -Level INFO
            } else {
                foreach ($item in $uniqueItems) {
                    # Reconstruire un objet compatible avec Invoke-ScanItem
                    # REST renvoie des hashtables, PnP renvoie des ListItem
                    if ($item -is [System.Collections.Hashtable] -or $item.PSObject.Properties["FileLeafRef"]) {
                        # Objet REST - charger via Get-PnPListItem pour avoir le bon type
                        $pnpItem = Get-PnPListItem -List $List.Id -Id $item.Id `
                            -Includes HasUniqueRoleAssignments, RoleAssignments
                        $fsoType  = $item.FSObjType
                        $itemType = if ($fsoType -eq 1) { "Folder" } else { "File" }
                        Invoke-ScanItem -SiteUrl $SiteUrl -SiteName $SiteName `
                            -ListTitle $List.Title -Item $pnpItem `
                            -ParentName $List.Title -ObjectType $itemType
                    } else {
                        $fsoType  = $item.FieldValues["FSObjType"]
                        $itemType = if ($fsoType -eq 1) { "Folder" } else { "File" }
                        Invoke-ScanItem -SiteUrl $SiteUrl -SiteName $SiteName `
                            -ListTitle $List.Title -Item $item `
                            -ParentName $List.Title -ObjectType $itemType
                    }
                }
            }
        }
    } catch {
        $Script:ScanErrors.Add([PSCustomObject]@{ Item = $List.Title; Error = $_.ToString() })
        Write-Log "  Error scanning list $($List.Title): $_" -Level WARN
    }
}

function Get-GroupMembers {
    param([string]$GroupTitle, [string]$LoginName, [string]$PrincipalType, [Nullable[int]]$SpGroupId = $null)
    if ($Script:GroupMembers.ContainsKey($GroupTitle)) { return }
    $members = @()
    try {
        if ($PrincipalType -eq "SP Group") {
            # ── Groupe SharePoint : membres via PnP ──
            $pnpMembers = Get-PnPGroupMember -Identity $GroupTitle -ErrorAction SilentlyContinue
            foreach ($m in $pnpMembers) {
                # Un membre de groupe SP peut lui-meme etre une revendication (claim) representant
                # tout le groupe AAD -> resoudre recursivement via Graph.
                # IMPORTANT : le suffixe "_o" a la fin du GUID indique specifiquement la revendication
                # "proprietaires du groupe" (utilisee par le groupe SP "Owners" d un site Team-connecte).
                # Sans ce suffixe, la revendication represente "membres du groupe". Ne pas distinguer
                # les deux fait que le groupe Owners affiche a tort les MEMBRES du groupe M365.
                if ($m.LoginName -match 'c:0t\.c\|tenant\|([0-9a-fA-F\-]{36})(_o)?' -or
                    $m.LoginName -match 'c:0o\.c\|federateddirectoryclaimprovider\|([0-9a-fA-F\-]{36})(_o)?') {
                    $nestedId      = $Matches[1]
                    $isOwnerClaim  = [bool]$Matches[2]  # "_o" present -> revendication proprietaires
                    if ($isOwnerClaim) {
                        $nestedResult = Get-AadGroupOwnersViaGraph -GroupId $nestedId
                    } else {
                        $nestedResult = Get-AadGroupMembersViaGraph -GroupId $nestedId
                    }
                    $nested = @($nestedResult.Members)
                    foreach ($nm in $nested) { $members += $nm }
                    if ($nested.Count -eq 0) {
                        # Garder au moins le groupe comme entree si resolution impossible
                        $suffix = if ($nestedResult.Orphaned) { " (groupe AAD supprime)" } else { "" }
                        $members += [PSCustomObject]@{ name="$($m.Title)$suffix"; email=$m.Email; login=$m.LoginName; type="Group" }
                    }
                } else {
                    # Filtrer le compte systeme SharePoint (SHAREPOINT\system), ajoute automatiquement
                    # aux groupes Owners mais qui n est pas un vrai proprietaire humain.
                    if ($m.LoginName -notmatch 'SHAREPOINT\\system' -and $m.Title -ne 'System Account') {
                        $members += [PSCustomObject]@{ name=$m.Title; email=$m.Email; login=$m.LoginName; type="User" }
                    }
                }
            }

            # ── Fallback Team site : le groupe SP Owners/Members d un site connecte a une
            # equipe M365 est une coquille vide (Get-PnPGroupMember renvoie 0, sans erreur).
            # Le vrai membership vit dans le groupe M365 associe -> on bascule sur Graph.
            #
            # IMPORTANT : le role (Owner/Member/Visitor) est determine par comparaison d ID
            # avec les groupes associes officiels du site (AssociatedOwnerGroup, etc.), PAS
            # par une regex sur le titre - qui echoue sur les tenants non-anglophones
            # (ex: "Proprietaires"/"Membres"/"Visiteurs" en francais).
            if ($members.Count -eq 0 -and $Script:CurrentSiteGroupId) {
                Write-Log "  Diagnostic '$GroupTitle' : SpGroupId=$SpGroupId Owner=$($Script:CurrentOwnerGroupId) Member=$($Script:CurrentMemberGroupId) Visitor=$($Script:CurrentVisitorGroupId)" -Level INFO
                if ($SpGroupId -and $Script:CurrentOwnerGroupId -and $SpGroupId -eq $Script:CurrentOwnerGroupId) {
                    Write-Log "  '$GroupTitle' vide via PnP - fallback Graph (owners) sur le groupe M365 du site" -Level INFO
                    $graphResult = Get-AadGroupOwnersViaGraph -GroupId $Script:CurrentSiteGroupId
                    $members = @($graphResult.Members)
                    if ($graphResult.Orphaned) { Write-Log "  Groupe M365 introuvable (supprime ?) : $Script:CurrentSiteGroupId" -Level WARN }
                } elseif ($SpGroupId -and $Script:CurrentMemberGroupId -and $SpGroupId -eq $Script:CurrentMemberGroupId) {
                    Write-Log "  '$GroupTitle' vide via PnP - fallback Graph (members) sur le groupe M365 du site" -Level INFO
                    $graphResult = Get-AadGroupMembersViaGraph -GroupId $Script:CurrentSiteGroupId
                    $members = @($graphResult.Members)
                    if ($graphResult.Orphaned) { Write-Log "  Groupe M365 introuvable (supprime ?) : $Script:CurrentSiteGroupId" -Level WARN }
                } elseif ($SpGroupId -and $Script:CurrentVisitorGroupId -and $SpGroupId -eq $Script:CurrentVisitorGroupId) {
                    # Le groupe Visitors n a pas d equivalent dans un groupe M365 - il est
                    # legitimement vide sur un Team site. On ne bascule PAS sur Graph ici :
                    # Get-PnPGroupMember a deja correctement renvoye 0 membre.
                    Write-Log "  '$GroupTitle' (Visitors) vide - normal sur un site Team-connecte, pas de fallback" -Level INFO
                } else {
                    # SpGroupId absent ou ne correspond a aucun groupe associe connu :
                    # ne pas deviner - on ne fait PAS de fallback pour eviter d afficher
                    # les mauvais membres sous le mauvais groupe.
                    Write-Log "  '$GroupTitle' vide via PnP - role non identifie, pas de fallback Graph" -Level INFO
                }
            }
        } elseif ($PrincipalType -eq "Security Group") {
            # ── Groupe AAD : extraire le GUID du LoginName et interroger Graph ──
            # Formats : c:0t.c|tenant|<guid>  (groupe de securite)
            #           c:0o.c|federateddirectoryclaimprovider|<guid>    (groupe M365)
            #           c:0o.c|federateddirectoryclaimprovider|<guid>_o  (proprietaires M365)
            $groupId = $null
            if ($LoginName -match '([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})') {
                $groupId = $Matches[1]
            }
            if ($groupId) {
                # Forcer le tableau : un retour vide serait sinon deroule en $null par PS
                $graphResult = Get-AadGroupMembersViaGraph -GroupId $groupId
                $members     = @($graphResult.Members)
                if ($graphResult.Orphaned) {
                    # Groupe supprime d AAD mais encore reference dans SharePoint :
                    # une permission fantome - info d audit utile !
                    Write-Log "  Groupe ORPHELIN detecte : '$GroupTitle' (supprime d Azure AD, permission a nettoyer)" -Level WARN
                    $members = @([PSCustomObject]@{
                        name  = "(Groupe supprime d Azure AD - permission orpheline a nettoyer)"
                        email = ""
                        login = $LoginName
                        type  = "Orphaned"
                    })
                }
            }
            if (-not $groupId) {
                Write-Log "  GUID introuvable dans le LoginName de '$GroupTitle'" -Level WARN
            }
        }
    } catch {
        Write-Log "  Erreur membres du groupe '$GroupTitle' : $_" -Level WARN
    }
    $Script:GroupMembers[$GroupTitle] = $members
}

function Get-AadGroupMembersViaGraph {
    <#
        Resout les membres d un groupe Azure AD via Microsoft Graph.
        Utilise transitiveMembers pour inclure les membres des groupes imbriques.
        Requiert la permission Graph GroupMember.Read.All (application).
        Retourne @{ Members = [tableau]; Orphaned = [bool] }
        Orphaned = true si le groupe n existe plus dans AAD (404).
    #>
    param([string]$GroupId)
    $result   = [System.Collections.Generic.List[PSCustomObject]]::new()
    $orphaned = $false
    try {
        # transitiveMembers = membres directs + membres des sous-groupes (ideal pour audit)
        $url = "https://graph.microsoft.com/v1.0/groups/$GroupId/transitiveMembers?`$select=displayName,mail,userPrincipalName&`$top=999"
        while ($url) {
            $resp = Invoke-PnPGraphMethod -Url $url -Method Get -ErrorAction Stop
            $vals = if ($resp.PSObject.Properties['value']) { @($resp.value) } else { @() }
            foreach ($m in $vals) {
                # Ne garder que les utilisateurs ; les groupes imbriques sont deja aplatis
                $odataType = if ($m.PSObject.Properties['@odata.type']) { $m.'@odata.type' } else { '' }
                if ($odataType -like '*user*' -or -not $odataType) {
                    $result.Add([PSCustomObject]@{
                        name  = $m.displayName
                        email = $(if ($m.mail) { $m.mail } else { $m.userPrincipalName })
                        login = $m.userPrincipalName
                        type  = "User"
                    })
                }
            }
            # Pagination Graph
            $url = if ($resp.PSObject.Properties['@odata.nextLink']) { $resp.'@odata.nextLink' } else { $null }
        }
    } catch {
        $msg = "$_"
        if ($msg -match 'does not exist|Request_ResourceNotFound|404') {
            # Groupe supprime d AAD - reference orpheline dans SharePoint
            $orphaned = $true
        } else {
            Write-Log "  Graph transitiveMembers KO pour $GroupId : $_" -Level WARN
        }
    }
    return @{ Members = @($result); Orphaned = $orphaned }
}

function Get-AadGroupOwnersViaGraph {
    <#
        Resout les proprietaires d un groupe Azure AD via Microsoft Graph.
        Utilise pour le groupe "Owners" d un site connecte a une equipe/groupe M365.
        Requiert la permission Graph GroupMember.Read.All (application).
        Retourne @{ Members = [tableau]; Orphaned = [bool] }
    #>
    param([string]$GroupId)
    $result   = [System.Collections.Generic.List[PSCustomObject]]::new()
    $orphaned = $false
    try {
        $url = "https://graph.microsoft.com/v1.0/groups/$GroupId/owners?`$select=displayName,mail,userPrincipalName&`$top=999"
        while ($url) {
            $resp = Invoke-PnPGraphMethod -Url $url -Method Get -ErrorAction Stop
            $vals = if ($resp.PSObject.Properties['value']) { @($resp.value) } else { @() }
            foreach ($m in $vals) {
                $result.Add([PSCustomObject]@{
                    name  = $m.displayName
                    email = $(if ($m.mail) { $m.mail } else { $m.userPrincipalName })
                    login = $m.userPrincipalName
                    type  = "User"
                })
            }
            $url = if ($resp.PSObject.Properties['@odata.nextLink']) { $resp.'@odata.nextLink' } else { $null }
        }
    } catch {
        $msg = "$_"
        if ($msg -match 'does not exist|Request_ResourceNotFound|404') {
            $orphaned = $true
        } else {
            Write-Log "  Graph owners KO pour $GroupId : $_" -Level WARN
        }
    }
    return @{ Members = @($result); Orphaned = $orphaned }
}

function Get-SPPermissions {
    # Extrait les permissions d un objet SharePoint via Get-PnPProperty (charge les sous-objets)
    param([object]$SecurableObject)
    if (-not $SecurableObject) { return @() }
    $perms = @()
    try {
        Get-PnPProperty -ClientObject $SecurableObject -Property HasUniqueRoleAssignments, RoleAssignments | Out-Null
        foreach ($ra in $SecurableObject.RoleAssignments) {
            Get-PnPProperty -ClientObject $ra -Property Member, RoleDefinitionBindings | Out-Null
            $levels = ($ra.RoleDefinitionBindings | Select-Object -ExpandProperty Name) -join ", "
            $login = $ra.Member.LoginName
            $type = switch -Wildcard ($ra.Member.PrincipalType.ToString()) {
                "User"            { "User" }
                "SharePointGroup" { "SP Group" }
                "SecurityGroup"   { "Security Group" }
                default           { $ra.Member.PrincipalType.ToString() }
            }

            # Detection des liens de partage (SharingLinks dans le LoginName)
            $shareType = ''
            if ($login -match 'SharingLinks') {
                $type = 'Lien de partage'
                if ($login -match 'Anonymous|Anonymous') {
                    if ($login -match 'Edit')     { $shareType = 'Anyone (modification)' }
                    else                          { $shareType = 'Anyone (lecture)' }
                } elseif ($login -match 'Organization') {
                    if ($login -match 'Edit')     { $shareType = 'Organisation (modification)' }
                    else                          { $shareType = 'Organisation (lecture)' }
                } elseif ($login -match 'Flexible') {
                    $shareType = 'Personnes specifiques'
                } else {
                    $shareType = 'Lien de partage'
                }
            }

            # Charger membres pour les groupes (pas pour les liens de partage)
            if ($type -in @("SP Group", "Security Group")) {
                $groupId = $null
                if ($type -eq "SP Group") {
                    try {
                        # Id n est pas toujours charge automatiquement sur RoleAssignment.Member -
                        # on force sa recuperation explicitement plutot que de supposer qu il est present.
                        Get-PnPProperty -ClientObject $ra.Member -Property Id -ErrorAction Stop | Out-Null
                        $groupId = [int]$ra.Member.Id
                    } catch {
                        Write-Log "  Impossible de lire Id du groupe '$($ra.Member.Title)' : $_" -Level WARN
                    }
                }
                Get-GroupMembers -GroupTitle $ra.Member.Title -LoginName $login -PrincipalType $type -SpGroupId $groupId
            }

            $principalName = if ($shareType) { $shareType } else { $ra.Member.Title }
            $perms += [PSCustomObject]@{
                Principal     = $principalName
                LoginName     = $login
                PrincipalType = $type
                PermLevel     = $levels
                ShareType     = $shareType
            }
        }
    } catch {
        Write-Log "Could not load permissions: $_" -Level WARN
    }
    return $perms
}

function Invoke-ScanSite {
    param([string]$Url)
    Write-Log "─── Scanning site: $Url" -Level SECTION

    try {
        Connect-ToSite -Url $Url

        $web = Get-PnPWeb -Includes Title, HasUniqueRoleAssignments, RoleAssignments, Url
        $siteName = $web.Title
        Write-Log "Site: $siteName" -Level OK

        # Detecter si le site est connecte a une equipe/groupe M365 (Team site).
        # Dans ce cas, les groupes SP Owners/Members/Visitors sont des "coquilles" vides -
        # le vrai membership vit dans le groupe M365 associe (via Graph).
        $Script:CurrentSiteGroupId    = $null
        $Script:CurrentOwnerGroupId   = $null
        $Script:CurrentMemberGroupId  = $null
        $Script:CurrentVisitorGroupId = $null
        try {
            $siteInfo = Get-PnPSite -Includes GroupId -ErrorAction SilentlyContinue
            if ($siteInfo -and $siteInfo.GroupId -and $siteInfo.GroupId -ne [Guid]::Empty) {
                $Script:CurrentSiteGroupId = $siteInfo.GroupId.ToString()
                Write-Log "  Site connecte a un groupe M365/Team : $Script:CurrentSiteGroupId" -Level INFO
            }
            # Identifier les 3 groupes associes PAR ID (fiable, independant de la langue du tenant -
            # un titre "Owners" en anglais ou "Proprietaires" en francais ne peut pas etre devine par regex).
            # IMPORTANT : le .Id des objets imbriques (AssociatedOwnerGroup, etc.) n est PAS charge
            # par un simple -Includes AssociatedOwnerGroup - il faut la notation pointee "Groupe.Id".
            # Chaque groupe est recupere dans son propre try/catch pour qu un echec sur l un
            # n empeche pas la resolution des deux autres.
            try {
                $webAssoc = Get-PnPWeb -Includes `
                    "AssociatedOwnerGroup.Id", "AssociatedOwnerGroup.Title", `
                    "AssociatedMemberGroup.Id", "AssociatedMemberGroup.Title", `
                    "AssociatedVisitorGroup.Id", "AssociatedVisitorGroup.Title" `
                    -ErrorAction Stop

                try {
                    if ($webAssoc.AssociatedOwnerGroup -and $webAssoc.AssociatedOwnerGroup.Id) {
                        $Script:CurrentOwnerGroupId = [int]$webAssoc.AssociatedOwnerGroup.Id
                    }
                } catch { Write-Log "  Impossible de lire AssociatedOwnerGroup.Id : $_" -Level WARN }

                try {
                    if ($webAssoc.AssociatedMemberGroup -and $webAssoc.AssociatedMemberGroup.Id) {
                        $Script:CurrentMemberGroupId = [int]$webAssoc.AssociatedMemberGroup.Id
                    }
                } catch { Write-Log "  Impossible de lire AssociatedMemberGroup.Id : $_" -Level WARN }

                try {
                    if ($webAssoc.AssociatedVisitorGroup -and $webAssoc.AssociatedVisitorGroup.Id) {
                        $Script:CurrentVisitorGroupId = [int]$webAssoc.AssociatedVisitorGroup.Id
                    }
                } catch { Write-Log "  Impossible de lire AssociatedVisitorGroup.Id : $_" -Level WARN }

                Write-Log "  Groupes associes - Owner:$($Script:CurrentOwnerGroupId) Member:$($Script:CurrentMemberGroupId) Visitor:$($Script:CurrentVisitorGroupId)" -Level INFO
            } catch {
                Write-Log "  Impossible de recuperer les groupes associes du site : $_" -Level WARN
            }
        } catch { }

        $sitePerms = Get-SPPermissions -SecurableObject $web

        Add-Result -SiteUrl $Url -SiteName $siteName `
            -ObjectType "Site" -ObjectName $siteName `
            -ObjectUrl $Url `
            -HasUniquePermissions $true `
            -InheritedFrom "" `
            -Permissions $sitePerms

        # Listes et bibliotheques (sauf si ScanDepth = Site)
        if ($ScanDepth -ne "Site") {
            $lists = Get-PnPList -Includes BaseType, HasUniqueRoleAssignments, DefaultViewUrl, Hidden, Id
            foreach ($list in $lists) {
                if ($list.Hidden) { continue }
                if ($ExcludeSystemLists -and ($Script:SystemLists -contains $list.Title.ToLower())) { continue }
                Invoke-ScanList -SiteUrl $Url -SiteName $siteName -List $list
            }
        } else {
            Write-Log "  ScanDepth=Site : listes/bibliotheques ignorees." -Level INFO
        }

        Disconnect-PnPOnline
    } catch {
        $Script:ScanErrors.Add([PSCustomObject]@{ Item = $Url; Error = $_.ToString() })
        Write-Log "Failed to scan site $Url : $_" -Level ERROR
        try { Disconnect-PnPOnline -ErrorAction SilentlyContinue } catch {}
    }
}
#endregion


#region ── REPORT ──

# ── Detection des risques ──────────────────────────────────────────────────────
function Get-RiskLevel {
    param([string]$Principal, [string]$LoginName, [string]$PermLevel, [string]$PrincipalType, [string]$ShareType = '')
    $risks = @()

    # Liens de partage - les "Anyone" sont les plus dangereux
    if ($ShareType) {
        if ($ShareType -like 'Anyone*') {
            $risks += "CRITIQUE: Lien de partage public ($ShareType)"
        } elseif ($ShareType -like 'Organisation*modification*') {
            $risks += "ELEVE: Lien organisation en modification"
        } elseif ($ShareType -like 'Organisation*') {
            $risks += "MOYEN: Lien de partage organisation ($ShareType)"
        }
    }

    if ($LoginName -match 'spo-grid-all-users|everyone except external|c:0\(.s\|true' -or
        $Principal -match '^Everyone|^All Users|^Tout le monde') {
        $risks += 'CRITIQUE: Acces public (Everyone)'
    }
    if ($LoginName -match '#ext#|urn:spo:guest') {
        $risks += 'ELEVE: Utilisateur externe'
    }
    if ($PermLevel -match 'Full Control' -and $PrincipalType -eq 'User') {
        $risks += 'ELEVE: Full Control direct sur un utilisateur'
    }
    if ($PermLevel -match 'Full Control' -and $PrincipalType -eq 'Security Group') {
        $risks += 'MOYEN: Full Control via groupe de securite'
    }
    if ($PermLevel -match 'Design|Edit' -and $PrincipalType -eq 'User') {
        $risks += 'MOYEN: Permission Edit/Design directe sur un utilisateur'
    }
    if ($risks.Count -eq 0) { return 'OK' }
    return ($risks -join ' | ')
}

# ── Aplatir les resultats en lignes CSV (reutilisable pour save incremental) ──
function ConvertTo-FlatRows {
    param([System.Collections.Generic.List[PSCustomObject]]$Results)
    $rows = [System.Collections.Generic.List[PSCustomObject]]::new()
    foreach ($r in $Results) {
        if ($r.Permissions -and $r.Permissions.Count -gt 0) {
            foreach ($p in $r.Permissions) {
                $shareType = if ($p.PSObject.Properties['ShareType']) { $p.ShareType } else { '' }
                $risk = Get-RiskLevel -Principal $p.Principal -LoginName $p.LoginName `
                    -PermLevel $p.PermLevel -PrincipalType $p.PrincipalType -ShareType $shareType
                $rows.Add([PSCustomObject]@{
                    SiteName             = $r.SiteName
                    SiteUrl              = $r.SiteUrl
                    ObjectType           = $r.ObjectType
                    ObjectName           = $r.ObjectName
                    ObjectUrl            = $r.ObjectUrl
                    HasUniquePermissions = $r.HasUniquePermissions
                    InheritedFrom        = $r.InheritedFrom
                    Principal            = $p.Principal
                    LoginName            = $p.LoginName
                    PrincipalType        = $p.PrincipalType
                    PermissionLevel      = $p.PermLevel
                    ShareType            = $shareType
                    Risk                 = $risk
                    ScannedAt            = $r.ScannedAt
                })
            }
        } else {
            $rows.Add([PSCustomObject]@{
                SiteName             = $r.SiteName
                SiteUrl              = $r.SiteUrl
                ObjectType           = $r.ObjectType
                ObjectName           = $r.ObjectName
                ObjectUrl            = $r.ObjectUrl
                HasUniquePermissions = $r.HasUniquePermissions
                InheritedFrom        = $r.InheritedFrom
                Principal            = ""
                LoginName            = ""
                PrincipalType        = ""
                PermissionLevel      = $(if ($r.HasUniquePermissions) { "(no assignments)" } else { "(inherited)" })
                ShareType            = ""
                Risk                 = "OK"
                ScannedAt            = $r.ScannedAt
            })
        }
    }
    return $rows
}

# ── Export CSV ─────────────────────────────────────────────────────────────────
function Export-CsvReport {
    param([string]$CsvPath)

    # En mode incremental, le CSV est deja ecrit au fil de l eau - on le relit pour
    # appliquer FocusUser et retourner les lignes au generateur HTML.
    if ($Script:CsvStreamPath -and (Test-Path $Script:CsvStreamPath)) {
        $rows = [System.Collections.Generic.List[PSCustomObject]](Import-Csv $Script:CsvStreamPath)
        Write-Log "Lecture du CSV incremental : $($rows.Count) lignes" -Level INFO
    } else {
        $rows = ConvertTo-FlatRows -Results $Script:ScanResults
    }

    if ($FocusUser) {
        # 1. Trouver tous les groupes dont l utilisateur est membre (lookup inverse)
        $userGroups = [System.Collections.Generic.List[string]]::new()
        foreach ($groupName in $Script:GroupMembers.Keys) {
            $members = $Script:GroupMembers[$groupName]
            foreach ($m in $members) {
                if (($m.email -and $m.email -like "*$FocusUser*") -or
                    ($m.name  -and $m.name  -like "*$FocusUser*") -or
                    ($m.login -and $m.login -like "*$FocusUser*")) {
                    if (-not $userGroups.Contains($groupName)) { $userGroups.Add($groupName) }
                    break
                }
            }
        }
        if ($userGroups.Count -gt 0) {
            Write-Log "FocusUser '$FocusUser' membre de $($userGroups.Count) groupe(s) : $($userGroups -join ', ')" -Level INFO
        }

        # 2. Filtrer : acces direct OU via un groupe dont l utilisateur est membre
        $filtered = [System.Collections.Generic.List[PSCustomObject]]::new()
        foreach ($r in $rows) {
            $isDirect = ($r.Principal -like "*$FocusUser*" -or $r.LoginName -like "*$FocusUser*")
            $viaGroup = $null
            foreach ($g in $userGroups) {
                if ($r.Principal -eq $g) { $viaGroup = $g; break }
            }
            if ($isDirect -or $viaGroup) {
                # Ajouter une colonne AccessVia pour indiquer comment l acces est accorde
                $r | Add-Member -NotePropertyName 'AccessVia' `
                    -NotePropertyValue $(if ($isDirect) { 'Direct' } else { "Groupe: $viaGroup" }) -Force
                $filtered.Add($r)
            }
        }
        $rows = $filtered
        Write-Log "FocusUser '$FocusUser' : $($rows.Count) lignes (direct + via groupes)" -Level INFO
    }
    $rows | Export-Csv -Path $CsvPath -Encoding UTF8 -NoTypeInformation -Force
    Write-Log "CSV : $CsvPath ($($rows.Count) lignes)" -Level OK
    return $rows
}

# ── Comparaison ────────────────────────────────────────────────────────────────
function Get-Comparison {
    param([string]$PreviousCsv, [string]$CurrentCsv)
    if (-not (Test-Path $PreviousCsv)) {
        Write-Log "CSV precedent introuvable : $PreviousCsv" -Level WARN
        return $null
    }
    Write-Log "Comparaison avec : $PreviousCsv" -Level INFO
    $prev = Import-Csv $PreviousCsv
    $curr = Import-Csv $CurrentCsv
    $prevKeys = @{}; foreach ($r in $prev) { $prevKeys["$($r.SiteUrl)|$($r.ObjectUrl)|$($r.Principal)|$($r.PermissionLevel)"] = $r }
    $currKeys = @{}; foreach ($r in $curr) { $currKeys["$($r.SiteUrl)|$($r.ObjectUrl)|$($r.Principal)|$($r.PermissionLevel)"] = $r }
    $added   = [System.Collections.Generic.List[PSCustomObject]]::new()
    $removed = [System.Collections.Generic.List[PSCustomObject]]::new()
    foreach ($k in $currKeys.Keys) { if (-not $prevKeys.ContainsKey($k)) { $added.Add($currKeys[$k]) } }
    foreach ($k in $prevKeys.Keys) { if (-not $currKeys.ContainsKey($k)) { $removed.Add($prevKeys[$k]) } }
    Write-Log "Diff : +$($added.Count) / -$($removed.Count)" -Level OK
    return @{ Added = $added; Removed = $removed }
}

# ── Rapport HTML ───────────────────────────────────────────────────────────────
function New-HtmlReport {
    Write-Log "Generating report..." -Level INFO

    $scanDuration = [math]::Round(((Get-Date) - $Script:StartTime).TotalSeconds, 1)
    $genDate      = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $errorCount   = $Script:ScanErrors.Count
    $csvPath      = $OutputPath -replace '\.html$', '.csv'
    $csvFileName  = [System.IO.Path]::GetFileName($csvPath)

    # 1. Exporter le CSV (lit le CSV incremental si present)
    $rows = Export-CsvReport -CsvPath $csvPath

    # Stats calculees depuis les lignes finales (compatible mode incremental)
    $uniqueCount  = @($rows | Where-Object { $_.HasUniquePermissions -eq $true -or $_.HasUniquePermissions -eq 'True' }).Count
    $siteCount    = @($rows | Where-Object { $_.ObjectType -eq "Site" }).Count

    # 2. Comparaison diff
    $addedJson   = '[]'
    $removedJson = '[]'
    $hasCompare  = 'false'
    $addedCount  = 0; $removedCount = 0
    if ($CompareWith) {
        $diff = Get-Comparison -PreviousCsv $CompareWith -CurrentCsv $csvPath
        if ($diff) {
            $hasCompare   = 'true'
            $addedCount   = $diff.Added.Count
            $removedCount = $diff.Removed.Count
            if ($addedCount   -gt 0) { $addedJson   = $diff.Added   | ConvertTo-Json -Compress -Depth 2 }
            if ($removedCount -gt 0) { $removedJson = $diff.Removed | ConvertTo-Json -Compress -Depth 2 }
            $diffCsv = $OutputPath -replace '\.html$', '_diff.csv'
            (@($diff.Added) + @($diff.Removed)) | Export-Csv $diffCsv -Encoding UTF8 -NoTypeInformation -Force
        }
    }

    # 3. Trouver le template
    # $PSScriptRoot est vide dans un Start-Job - on essaie plusieurs emplacements
    $templatePath = $null
    $candidates = @(
        (Join-Path $PSScriptRoot         "SPPermissions_template.html"),  # Normal
        (Join-Path (Get-Location).Path   "SPPermissions_template.html"),  # Working dir
        (Join-Path $env:SP_SCANNER_DIR   "SPPermissions_template.html"),  # Via env var (Start-Job)
        (Join-Path (Split-Path $OutputPath -Parent) "SPPermissions_template.html")  # Cote du rapport
    )
    foreach ($c in $candidates) {
        if ($c -and (Test-Path $c)) { $templatePath = $c; break }
    }
    if (-not $templatePath) {
        Write-Log "Template SPPermissions_template.html introuvable." -Level ERROR
        Write-Log "Emplacements essayes : $($candidates -join ', ')" -Level WARN
        Write-Log "Placez SPPermissions_template.html dans le meme dossier que le script." -Level WARN
        return
    }
    Write-Log "Template : $templatePath" -Level INFO

    # 4. Lire le template et injecter les placeholders (remplacements simples et fiables)
    $metaJson = [ordered]@{
        generatedAt = $genDate
        mode        = $Mode
        scanDepth   = $ScanDepth
        duration    = $scanDuration
        errors      = $errorCount
        totalRows   = $rows.Count
        focusUser   = $FocusUser
    } | ConvertTo-Json -Compress

    # Serialiser les membres de groupes
    $groupMembersJson = if ($Script:GroupMembers.Count -gt 0) {
        $gmObj = @{}
        foreach ($key in $Script:GroupMembers.Keys) { $gmObj[$key] = $Script:GroupMembers[$key] }
        $gmObj | ConvertTo-Json -Compress -Depth 4
    } else { '{}' }

    $html = [System.IO.File]::ReadAllText($templatePath, [System.Text.Encoding]::UTF8)
    $html = $html.Replace('__CSV_FILENAME__',   $csvFileName)
    $html = $html.Replace('__META_JSON__',      $metaJson)
    $html = $html.Replace('__DIFF_ADDED__',     $addedJson)
    $html = $html.Replace('__DIFF_REMOVED__',   $removedJson)
    $html = $html.Replace('__HAS_COMPARE__',    $hasCompare)
    $html = $html.Replace('__GROUP_MEMBERS__',  $groupMembersJson)

    # Embarquer les donnees directement dans le HTML pour qu il fonctionne aussi
    # en double-clic (file://) sans dependre du fetch CSV bloque par CORS.
    $dataJson = if ($rows.Count -gt 0) {
        $rows | ConvertTo-Json -Compress -Depth 3
    } else { '[]' }
    # ConvertTo-Json sur un seul element ne produit pas un tableau - forcer les crochets
    if ($rows.Count -eq 1) { $dataJson = "[$dataJson]" }

    # SECURITE : echapper "<" en "\u003c" pour eviter qu un "</script>" present dans
    # les donnees (nom de fichier, URL...) ne ferme le bloc script prematurement.
    # JavaScript redecode \u003c en "<", donc les donnees restent correctes.
    $escLt = { param($s) if ($s) { $s.Replace('<', '\u003c') } else { $s } }
    $dataJson    = & $escLt $dataJson
    $metaEsc     = & $escLt $metaJson
    $addedEsc    = & $escLt $addedJson
    $removedEsc  = & $escLt $removedJson

    $embedScript = "<script>window.__EMBEDDED__={data:$dataJson,meta:$metaEsc,added:$addedEsc,removed:$removedEsc};</script>"
    # Injecter avant le PREMIER </head> uniquement
    $headIdx = $html.IndexOf('</head>')
    if ($headIdx -ge 0) {
        $html = $html.Substring(0, $headIdx) + $embedScript + $html.Substring($headIdx)
    } else {
        Write-Log "Balise </head> introuvable dans le template" -Level WARN
    }

    [System.IO.File]::WriteAllText($OutputPath, $html, [System.Text.Encoding]::UTF8)
    Write-Log "HTML : $OutputPath" -Level OK
    Write-Log "CSV  : $csvPath"    -Level OK
}


#endregion


try {
    # Validate parameters
    if ($Mode -eq "SingleSite" -and -not $SiteUrl)       { throw "SiteUrl is required for SingleSite mode." }
    if ($Mode -eq "SiteCollection" -and -not $SiteUrl)   { throw "SiteUrl is required for SiteCollection mode." }
    if ($Mode -eq "AllSites" -and -not $TenantAdminUrl)  { throw "TenantAdminUrl is required for AllSites mode." }

    # Show auth params for troubleshooting
    Write-Log "Auth params received :" -Level INFO
    Write-Log "  ClientId   = '$ClientId'" -Level INFO
    Write-Log "  Thumbprint = '$Thumbprint'" -Level INFO
    Write-Log "  Tenant     = '$Tenant'" -Level INFO

    # Check certificate in store if thumbprint provided
    if ($Thumbprint) {
        $certUser    = Get-Item "Cert:\CurrentUser\My\$Thumbprint"  -ErrorAction SilentlyContinue
        $certMachine = Get-Item "Cert:\LocalMachine\My\$Thumbprint" -ErrorAction SilentlyContinue
        if ($certUser)    { Write-Log "Certificate found in CurrentUser\My store." -Level OK }
        elseif ($certMachine) { Write-Log "Certificate found in LocalMachine\My store." -Level OK }
        else {
            Write-Log "Certificate NOT found in any store! Thumbprint: $Thumbprint" -Level WARN
            Write-Log "Run: Import-PfxCertificate -FilePath '<path>.pfx' -CertStoreLocation Cert:\CurrentUser\My" -Level WARN
        }
    }

    # Check PnP module
    # Verifier PnP.PowerShell
    if (-not (Get-Module -ListAvailable -Name "PnP.PowerShell")) {
        Write-Log "PnP.PowerShell non installe. Lancez : Install-Module PnP.PowerShell -Scope CurrentUser" -Level ERROR
        exit 1
    }
    # Importer PnP proprement en evitant les conflits d assemblies Microsoft.Graph
    # Si Microsoft.Graph SDK est deja charge dans la session, PnP peut entrer en conflit.
    # Solution : ne pas importer explicitement (PnP.PowerShell s auto-importe via ses cmdlets)
    # et ignorer les erreurs d assembly non critiques.
    if (-not (Get-Module -Name "PnP.PowerShell")) {
        try {
            Import-Module PnP.PowerShell -ErrorAction Stop -WarningAction SilentlyContinue
            Write-Log "PnP.PowerShell charge." -Level OK
        } catch {
            if ($_.Exception.Message -like "*Assembly*already loaded*" -or
                $_.Exception.Message -like "*Could not load file or assembly*") {
                Write-Log "Avertissement assembly Graph (non bloquant) - le script continue." -Level WARN
            } else {
                Write-Log "Erreur chargement PnP.PowerShell : $_" -Level ERROR
                Write-Log "Conseil : Ouvrez une nouvelle session PowerShell et relancez le script." -Level WARN
                exit 1
            }
        }
    }

    # Choix interactif du ScanDepth si pas specifie (valeur par defaut)
    if (-not $PSBoundParameters.ContainsKey('ScanDepth')) {
        Write-Host ""
        Write-Host "  Profondeur de scan :" -ForegroundColor Cyan
        Write-Host "  [1] Site uniquement                          (tres rapide)" -ForegroundColor White
        Write-Host "  [2] Site + Bibliotheques/Listes              (rapide - recommande)" -ForegroundColor White
        Write-Host "  [3] Site + Bibliotheques + Dossiers/Fichiers (lent)" -ForegroundColor White
        Write-Host ""
        Write-Host "  Votre choix [1/2/3] (defaut: 2) : " -NoNewline -ForegroundColor Yellow
        $choice = Read-Host
        $ScanDepth = switch ($choice) {
            "1" { "Site" }
            "3" { "Full" }
            default { "SiteAndLibraries" }
        }
        Write-Log "ScanDepth selectionne : $ScanDepth" -Level OK
    }

    # Orchestration du scan
    Write-Log "═══════════════════════════════════════════════" -Level SECTION
    Write-Log "  SharePoint Permission Scanner  v1.0" -Level SECTION
    Write-Log "  Mode      : $Mode" -Level SECTION
    Write-Log "  ScanDepth : $ScanDepth" -Level SECTION
    Write-Log "═══════════════════════════════════════════════" -Level SECTION

    switch ($Mode) {
        "SingleSite" {
            Invoke-ScanSite -Url $SiteUrl
        }
        "SiteCollection" {
            Connect-ToSite -Url $SiteUrl
            $subsiteUrls = @(Get-PnPSubWeb -Recurse | Select-Object -ExpandProperty Url)
            Disconnect-PnPOnline
            Invoke-ScanSite -Url $SiteUrl
            foreach ($subUrl in $subsiteUrls) { Invoke-ScanSite -Url $subUrl }
        }
        "AllSites" {
            if (-not $TenantAdminUrl) { throw "TenantAdminUrl is required for AllSites mode." }
            Connect-ToSite -Url $TenantAdminUrl
            $allSites = Get-PnPTenantSite -IncludeOneDriveSites:$IncludeOneDrive | Select-Object -ExpandProperty Url

            if ($IncludeOneDrive) {
                Write-Log "OneDrive personnels INCLUS dans le scan" -Level INFO
            } else {
                # Double securite : filtrer explicitement les URL OneDrive
                # (Get-PnPTenantSite peut retourner des sites -my.sharepoint.com malgre le switch)
                $beforeCount = $allSites.Count
                $allSites = $allSites | Where-Object {
                    $_ -notmatch '-my\.sharepoint\.com' -and $_ -notmatch '/personal/'
                }
                $excluded = $beforeCount - $allSites.Count
                Write-Log "OneDrive personnels EXCLUS : $excluded site(s) filtre(s) (utilisez -IncludeOneDrive `$true pour les inclure)" -Level INFO
            }
            Disconnect-PnPOnline

            # ── RESILIENCE : sauvegarde incrementale + checkpoint ──
            $csvPathForSave = $OutputPath -replace '\.html$', '.csv'
            Initialize-IncrementalSave -CsvPath $csvPathForSave

            # Filtrer les sites deja scannes (mode -Resume)
            $toScan = @($allSites | Where-Object { -not $Script:CompletedSites.Contains($_) })
            $totalSites = $toScan.Count
            $skipped    = $allSites.Count - $totalSites
            if ($skipped -gt 0) {
                Write-Log "Reprise : $skipped site(s) deja scanne(s) ignores, $totalSites restant(s)" -Level OK
            }
            Write-Log "Found $($allSites.Count) sites ($totalSites a scanner)." -Level OK

            $idx = 0
            foreach ($siteUrl in $toScan) {
                $idx++
                # Progression + ETA
                $elapsed = (Get-Date) - $Script:StartTime
                $eta = ""
                if ($idx -gt 1) {
                    $perSite = $elapsed.TotalSeconds / ($idx - 1)
                    $remain  = [TimeSpan]::FromSeconds($perSite * ($totalSites - $idx + 1))
                    $eta = " - ETA ~$([math]::Floor($remain.TotalMinutes))min"
                }
                Write-Log "[$idx/$totalSites] $siteUrl$eta" -Level SECTION

                # Reconnexion preventive du token (scans longs)
                Test-TokenRefresh -Url $siteUrl

                try {
                    # Le scan d un site avec retry sur throttling
                    Invoke-WithRetry -Context $siteUrl -Action { Invoke-ScanSite -Url $siteUrl }
                    # Persister immediatement les resultats de ce site
                    Save-SiteResults -SiteUrl $siteUrl
                } catch {
                    Write-Log "Site ignore apres echec : $siteUrl - $_" -Level ERROR
                    $Script:ScanErrors.Add([PSCustomObject]@{ Site = $siteUrl; Error = "$_" })
                    # On marque quand meme le site comme traite pour ne pas boucler en -Resume
                    Save-SiteResults -SiteUrl $siteUrl
                }
            }
        }
    }

    Write-Log "Scan complete. Total objects scanned: $Script:TotalScanned" -Level OK
    New-HtmlReport

    # Nettoyer le checkpoint apres un scan complet reussi
    if ($Script:CheckpointPath -and (Test-Path $Script:CheckpointPath)) {
        Remove-Item $Script:CheckpointPath -Force -ErrorAction SilentlyContinue
        Write-Log "Checkpoint supprime (scan termine avec succes)" -Level INFO
    }

    Write-Log "═══════════════════════════════════" -Level SECTION
    Write-Log "  Done! Report: $OutputPath" -Level OK
    Write-Log "═══════════════════════════════════" -Level SECTION


    # Ouvrir le rapport - uniquement en mode interactif
    # En mode non-interactif (Start-SPScanner.ps1), on saute cette etape
    if ([Environment]::UserInteractive -and -not ([Console]::IsInputRedirected)) {
        try {
            $openReport = Read-Host "Open report in browser? (Y/N)"
            if ($openReport -eq "Y") {
                $absPath = (Resolve-Path $OutputPath -ErrorAction SilentlyContinue | Select-Object -ExpandProperty Path -ErrorAction SilentlyContinue)
                if (-not $absPath) { $absPath = $OutputPath }
                Start-Process "explorer.exe" -ArgumentList "`"$absPath`""
            }
        } catch { }
    }

} catch {
    Write-Log "Fatal error: $_" -Level ERROR
    Write-Log $_.ScriptStackTrace -Level ERROR
    exit 1
}

#endregion