<#
.SYNOPSIS
    SharePoint Permission Scanner - Generates a detailed HTML report of all permissions
    across SharePoint sites, libraries, folders, and files.

.DESCRIPTION
    This script connects to SharePoint Online using PnP PowerShell and recursively
    scans permissions at all levels: Site, Lists/Libraries, Folders, and Files.
    It detects broken inheritance and exports a rich interactive HTML report.

.PARAMETER Mode
    Scanning mode:
      - SingleSite     : Scan a single SharePoint site
      - AllSites       : Scan all sites in the tenant
      - SiteCollection : Scan a specific site collection (root + subsites)

.PARAMETER SiteUrl
    URL of the SharePoint site (required for SingleSite and SiteCollection modes).

.PARAMETER TenantAdminUrl
    URL of the SharePoint Admin Center (e.g. https://contoso-admin.sharepoint.com).
    Required for AllSites mode.

.PARAMETER OutputPath
    Path and filename for the HTML report. Defaults to .\SPPermissions_<timestamp>.html

.PARAMETER IncludeFiles
    If set, scans individual file permissions (slower but more thorough). Default: $true

.PARAMETER MaxFileDepth
    Maximum folder depth to scan for files. Default: 10

.PARAMETER ExcludeSystemLists
    Exclude SharePoint system lists (Style Library, Site Assets, etc.). Default: $true

.PARAMETER ClientId
    Azure AD App Registration Client ID for app-only authentication.

.PARAMETER Thumbprint
    Certificate thumbprint for app-only authentication.

.PARAMETER Tenant
    Tenant ID or domain for app-only authentication.

.EXAMPLE
    # Interactive login - Single site
    .\SPPermissionScanner.ps1 -Mode SingleSite -SiteUrl "https://contoso.sharepoint.com/sites/HR"

.EXAMPLE
    # All sites in tenant
    .\SPPermissionScanner.ps1 -Mode AllSites -TenantAdminUrl "https://contoso-admin.sharepoint.com"

.EXAMPLE
    # App-only auth - Site collection
    .\SPPermissionScanner.ps1 -Mode SiteCollection -SiteUrl "https://contoso.sharepoint.com/sites/Projects" `
        -ClientId "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" `
        -Thumbprint "ABCDEF1234567890" `
        -Tenant "contoso.onmicrosoft.com"

.NOTES
    Author  : Generated by Claude
    Version : 1.0
    Requires: PnP.PowerShell module (Install-Module PnP.PowerShell)
    
    Required permissions (App-only):
      - Sites.FullControl.All (SharePoint)
      - Directory.Read.All (Graph - for user/group details)
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [ValidateSet("SingleSite", "AllSites", "SiteCollection")]
    [string]$Mode,

    [Parameter()]
    [string]$SiteUrl,

    [Parameter()]
    [string]$TenantAdminUrl,

    [Parameter()]
    [string]$OutputPath = ".\SPPermissions_$(Get-Date -Format 'yyyyMMdd_HHmmss').html",

    [Parameter()]
    [ValidateSet("Site", "SiteAndLibraries", "Full")]
    [string]$ScanDepth = "SiteAndLibraries",
    # Site              : Site uniquement (permissions du site)
    # SiteAndLibraries  : Site + Listes/Bibliotheques (recommande, rapide)
    # Full              : Site + Bibliotheques + Dossiers + Fichiers (lent)

    [Parameter()]
    [bool]$ExcludeSystemLists = $true,

    [Parameter()]
    [string]$ClientId,

    [Parameter()]
    [string]$Thumbprint,


    [Parameter()]
    [string]$ClientSecret,
    # Alternative au certificat : client secret Azure AD
    [Parameter()]
    [string]$Tenant,

    [Parameter()]
    [string]$FocusUser,
    # Filtrer par utilisateur/groupe : ne retourne que les objets ou ce principal a acces
    # Ex: -FocusUser "john.doe@contoso.com"

    [Parameter()]
    [string]$CompareWith
    # CSV d un scan precedent pour comparaison avant/apres
    # Ex: -CompareWith ".\SPPermissions_20260501.csv"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

#region ──────────────────────── GLOBALS ────────────────────────

$Script:ScanResults   = [System.Collections.Generic.List[PSCustomObject]]::new()
$Script:ScanErrors    = [System.Collections.Generic.List[PSCustomObject]]::new()
$Script:TotalScanned  = 0
$Script:StartTime     = Get-Date
$Script:SystemLists   = @(
    "appdata", "appfiles", "composed looks", "converted forms",
    "form templates", "list template gallery", "master page gallery",
    "preservation hold library", "site collection images",
    "site pages", "solution gallery", "style library",
    "theme gallery", "user information list", "web part gallery",
    "site assets", "cache profiles", "content and structure reports",
    "content type publishing error log", "customized reports",
    "designated sites", "devices", "hold reports", "relationships list",
    "reusable content", "suggested content browser locations",
    "taxonomy hidden list", "translation status", "wfpub", "wfsvc"
)

#endregion

#region ──────────────────────── HELPERS ────────────────────────

function Write-Log {
    param([string]$Message, [string]$Level = "INFO")
    $timestamp = Get-Date -Format "HH:mm:ss"
    $color = switch ($Level) {
        "INFO"    { "Cyan" }
        "OK"      { "Green" }
        "WARN"    { "Yellow" }
        "ERROR"   { "Red" }
        "SECTION" { "Magenta" }
        default   { "White" }
    }
    Write-Host "[$timestamp] " -NoNewline -ForegroundColor DarkGray
    Write-Host "[$Level] " -NoNewline -ForegroundColor $color
    Write-Host $Message
}

function Add-Result {
    param(
        [string]$SiteUrl,
        [string]$SiteName,
        [string]$ObjectType,   # Site | Library | List | Folder | File
        [string]$ObjectName,
        [string]$ObjectUrl,
        [bool]$HasUniquePermissions,
        [string]$InheritedFrom,
        [PSCustomObject[]]$Permissions
    )
    $Script:ScanResults.Add([PSCustomObject]@{
        SiteUrl              = $SiteUrl
        SiteName             = $SiteName
        ObjectType           = $ObjectType
        ObjectName           = $ObjectName
        ObjectUrl            = $ObjectUrl
        HasUniquePermissions = $HasUniquePermissions
        InheritedFrom        = $InheritedFrom
        Permissions          = $Permissions
        ScannedAt            = (Get-Date -Format "o")
    })
    $Script:TotalScanned++
}



#endregion

#region ──────────────────────── CONNECT ────────────────────────

function Connect-ToSite {
    param([string]$Url)
    Write-Log "Connecting to: $Url" -Level INFO
    try {
        if ($ClientId -and $ClientSecret -and $Tenant) {
            # Authentification par Client Secret (pas de certificat requis)
            Write-Log "Auth: Client Secret" -Level INFO
            Connect-PnPOnline -Url $Url -ClientId $ClientId -ClientSecret $ClientSecret -Tenant $Tenant -ErrorAction Stop
        } elseif ($ClientId -and $Thumbprint -and $Tenant) {
            # Verify certificate exists in store
            $cert = Get-Item "Cert:\CurrentUser\My\$Thumbprint" -ErrorAction SilentlyContinue
            if (-not $cert) {
                $cert = Get-Item "Cert:\LocalMachine\My\$Thumbprint" -ErrorAction SilentlyContinue
            }
            if (-not $cert) {
                throw "Certificate with thumbprint '$Thumbprint' not found in CurrentUser\My or LocalMachine\My store. Import the .pfx file first: Import-PfxCertificate -FilePath '<path>.pfx' -CertStoreLocation Cert:\CurrentUser\My"
            }
            Write-Log "Certificate found: $($cert.Subject) (expires $($cert.NotAfter.ToString('yyyy-MM-dd')))" -Level OK
            # App-only auth with certificate thumbprint
            Connect-PnPOnline -Url $Url `
                -ClientId $ClientId `
                -Thumbprint $Thumbprint `
                -Tenant $Tenant `
                -ErrorAction Stop
        } elseif ($ClientId -and $Tenant) {
            # App-only auth - interactive device login
            Connect-PnPOnline -Url $Url `
                -ClientId $ClientId `
                -Tenant $Tenant `
                -Interactive `
                -ErrorAction Stop
        } else {
            # Delegated interactive login (uses PnP community app)
            Connect-PnPOnline -Url $Url -Interactive -ErrorAction Stop
        }
        Write-Log "Connected successfully." -Level OK
    } catch {
        Write-Log "Connection failed: $_" -Level ERROR
        throw
    }
}

#endregion

#region ──────────────────────── SCAN FUNCTIONS ────────────────────────

function Invoke-ScanItem {
    param(
        [string]$SiteUrl,
        [string]$SiteName,
        [string]$ListTitle,
        [object]$Item,
        [string]$ParentName,
        [string]$ObjectType
    )
    try {
        $hasUnique = $Item.HasUniqueRoleAssignments
        $name = if ($Item.FieldValues["FileLeafRef"]) { $Item.FieldValues["FileLeafRef"] } else { $Item.FieldValues["Title"] }
        $ref  = $Item.FieldValues["FileRef"]
        $url  = if ($ref) { "$SiteUrl$ref" } else { $SiteUrl }

        # Charger les permissions uniquement si l item a des permissions uniques
        # Si herite, ses permissions = parent -> pas besoin de charger (et on ne devrait
        # pas arriver ici grace au filtrage dans Invoke-ScanList)
        $perms = if ($hasUnique) {
            Get-SPPermissions -SecurableObject $Item
        } else { @() }

        Add-Result -SiteUrl $SiteUrl -SiteName $SiteName `
            -ObjectType $ObjectType -ObjectName $name `
            -ObjectUrl $url `
            -HasUniquePermissions $hasUnique `
            -InheritedFrom $(if ($hasUnique) { [string]::Empty } else { $ParentName }) `
            -Permissions $perms

        $icon = if ($ObjectType -eq "Folder") { "F" } else { "D" }
        Write-Log "  [$icon] $ObjectType : $name | Unique: $hasUnique" -Level INFO
    } catch {
        $Script:ScanErrors.Add([PSCustomObject]@{ Item = "$ListTitle/$($Item.Id)"; Error = $_.ToString() })
        Write-Log "  Error scanning $ObjectType $($Item.Id): $_" -Level WARN
    }
}

function Invoke-ScanList {
    param(
        [string]$SiteUrl,
        [string]$SiteName,
        [object]$List
    )
    $listType = if ($List.BaseType -eq "DocumentLibrary") { "Library" } else { "List" }
    Write-Log "  📚 Scanning $listType : $($List.Title)" -Level INFO

    try {
        # Permissions de la liste/bibliotheque (toujours chargees, heritees ou uniques)
        $listFull  = Get-PnPList -Identity $List.Id -Includes HasUniqueRoleAssignments, RoleAssignments
        $hasUnique = $listFull.HasUniqueRoleAssignments

        # On charge toujours les permissions effectives (meme si heritees du site)
        $perms = Get-SPPermissions -SecurableObject $listFull

        Add-Result -SiteUrl $SiteUrl -SiteName $SiteName `
            -ObjectType $listType -ObjectName $List.Title `
            -ObjectUrl "$SiteUrl$($List.DefaultViewUrl)" `
            -HasUniquePermissions $hasUnique `
            -InheritedFrom $(if ($hasUnique) { [string]::Empty } else { $SiteName }) `
            -Permissions $perms

        # Scanner les items selon le ScanDepth
        if ($ScanDepth -eq "Full" -and $List.BaseType -eq "DocumentLibrary") {

            # Optimisation : si la librairie herite du site, ses items heritent aussi en cascade.
            # Inutile de scanner chaque item — on saute directement.
            if (-not $hasUnique) {
                Write-Log "    [SKIP] $($List.Title) herite ses permissions - items non scannes." -Level INFO
            } else {
                # La librairie a des permissions uniques : recuperer les items via REST
                # (HasUniqueRoleAssignments disponible en un seul appel REST, pas via -Includes PnP)
                $listId   = $List.Id
                $restUrl  = "/_api/web/lists(guid'$listId')/items?" +
                            "`$select=Id,FileLeafRef,FileRef,FSObjType,HasUniqueRoleAssignments" +
                            "&`$top=5000"

                try {
                    $restResult  = Invoke-PnPSPRestMethod -Url $restUrl -Method Get
                    $allItems    = @($restResult.value)
                    $uniqueItems = @($allItems | Where-Object { $_.HasUniqueRoleAssignments -eq $true })
                } catch {
                    # Fallback : Get-PnPListItem sans HasUniqueRoleAssignments, puis check individuel
                    Write-Log "    REST fallback: $_ - utilisation de Get-PnPListItem" -Level WARN
                    $pnpItems    = @(Get-PnPListItem -List $List.Id `
                        -Fields "FileLeafRef","FileRef","FSObjType" -PageSize 500)
                    $allItems    = $pnpItems
                    # Charger HasUniqueRoleAssignments item par item (plus lent)
                    $uniqueItems = @($pnpItems | Where-Object {
                        try {
                            Get-PnPProperty -ClientObject $_ -Property HasUniqueRoleAssignments | Out-Null
                            $_.HasUniqueRoleAssignments
                        } catch { $false }
                    })
                }

                $totalItems = $allItems.Count
                Write-Log "    $totalItems items dans $($List.Title) - $($uniqueItems.Count) avec permissions uniques" -Level INFO

                if ($uniqueItems.Count -eq 0) {
                    Write-Log "    [SKIP] Aucun item avec permissions uniques." -Level INFO
                } else {
                    foreach ($item in $uniqueItems) {
                        # Reconstruire un objet compatible avec Invoke-ScanItem
                        # REST renvoie des hashtables, PnP renvoie des ListItem
                        if ($item -is [System.Collections.Hashtable] -or $item.PSObject.Properties["FileLeafRef"]) {
                            # Objet REST - charger via Get-PnPListItem pour avoir le bon type
                            $pnpItem = Get-PnPListItem -List $List.Id -Id $item.Id `
                                -Includes HasUniqueRoleAssignments, RoleAssignments
                            $fsoType  = $item.FSObjType
                            $itemType = if ($fsoType -eq 1) { "Folder" } else { "File" }
                            Invoke-ScanItem -SiteUrl $SiteUrl -SiteName $SiteName `
                                -ListTitle $List.Title -Item $pnpItem `
                                -ParentName $List.Title -ObjectType $itemType
                        } else {
                            $fsoType  = $item.FieldValues["FSObjType"]
                            $itemType = if ($fsoType -eq 1) { "Folder" } else { "File" }
                            Invoke-ScanItem -SiteUrl $SiteUrl -SiteName $SiteName `
                                -ListTitle $List.Title -Item $item `
                                -ParentName $List.Title -ObjectType $itemType
                        }
                    }
                }
            }
        }
    } catch {
        $Script:ScanErrors.Add([PSCustomObject]@{ Item = $List.Title; Error = $_.ToString() })
        Write-Log "  Error scanning list $($List.Title): $_" -Level WARN
    }
}

function Get-SPPermissions {
    # Extrait les permissions d un objet SharePoint via Get-PnPProperty (charge les sous-objets)
    param([object]$SecurableObject)
    $perms = @()
    try {
        Get-PnPProperty -ClientObject $SecurableObject -Property HasUniqueRoleAssignments, RoleAssignments | Out-Null
        foreach ($ra in $SecurableObject.RoleAssignments) {
            Get-PnPProperty -ClientObject $ra -Property Member, RoleDefinitionBindings | Out-Null
            $levels = ($ra.RoleDefinitionBindings | Select-Object -ExpandProperty Name) -join ", "
            $type = switch -Wildcard ($ra.Member.PrincipalType.ToString()) {
                "User"            { "User" }
                "SharePointGroup" { "SP Group" }
                "SecurityGroup"   { "Security Group" }
                default           { $ra.Member.PrincipalType.ToString() }
            }
            $perms += [PSCustomObject]@{
                Principal     = $ra.Member.Title
                LoginName     = $ra.Member.LoginName
                PrincipalType = $type
                PermLevel     = $levels
            }
        }
    } catch {
        Write-Log "Could not load permissions: $_" -Level WARN
    }
    return $perms
}

function Invoke-ScanSite {
    param([string]$Url)
    Write-Log "─── Scanning site: $Url" -Level SECTION

    try {
        Connect-ToSite -Url $Url

        $web = Get-PnPWeb -Includes Title, HasUniqueRoleAssignments, RoleAssignments, Url
        $siteName = $web.Title
        Write-Log "Site: $siteName" -Level OK

        $sitePerms = Get-SPPermissions -SecurableObject $web

        Add-Result -SiteUrl $Url -SiteName $siteName `
            -ObjectType "Site" -ObjectName $siteName `
            -ObjectUrl $Url `
            -HasUniquePermissions $true `
            -InheritedFrom "" `
            -Permissions $sitePerms

        # Listes et bibliotheques (sauf si ScanDepth = Site)
        if ($ScanDepth -ne "Site") {
            $lists = Get-PnPList -Includes BaseType, HasUniqueRoleAssignments, DefaultViewUrl, Hidden, Id
            foreach ($list in $lists) {
                if ($list.Hidden) { continue }
                if ($ExcludeSystemLists -and ($Script:SystemLists -contains $list.Title.ToLower())) { continue }
                Invoke-ScanList -SiteUrl $Url -SiteName $siteName -List $list
            }
        } else {
            Write-Log "  ScanDepth=Site : listes/bibliotheques ignorees." -Level INFO
        }

        Disconnect-PnPOnline
    } catch {
        $Script:ScanErrors.Add([PSCustomObject]@{ Item = $Url; Error = $_.ToString() })
        Write-Log "Failed to scan site $Url : $_" -Level ERROR
        try { Disconnect-PnPOnline -ErrorAction SilentlyContinue } catch {}
    }
}
#endregion


#region ── REPORT ──

# ── Detection des risques ──────────────────────────────────────────────────────
function Get-RiskLevel {
    param([string]$Principal, [string]$LoginName, [string]$PermLevel, [string]$PrincipalType)
    $risks = @()
    if ($LoginName -match 'spo-grid-all-users|everyone except external|c:0\(.s\|true' -or
        $Principal -match '^Everyone|^All Users|^Tout le monde') {
        $risks += 'CRITIQUE: Acces public (Everyone)'
    }
    if ($LoginName -match '#ext#|urn:spo:guest') {
        $risks += 'ELEVE: Utilisateur externe'
    }
    if ($PermLevel -match 'Full Control' -and $PrincipalType -eq 'User') {
        $risks += 'ELEVE: Full Control direct sur un utilisateur'
    }
    if ($PermLevel -match 'Full Control' -and $PrincipalType -eq 'Security Group') {
        $risks += 'MOYEN: Full Control via groupe de securite'
    }
    if ($PermLevel -match 'Design|Edit' -and $PrincipalType -eq 'User') {
        $risks += 'MOYEN: Permission Edit/Design directe sur un utilisateur'
    }
    if ($risks.Count -eq 0) { return 'OK' }
    return ($risks -join ' | ')
}

# ── Export CSV ─────────────────────────────────────────────────────────────────
function Export-CsvReport {
    param([string]$CsvPath)
    $rows = [System.Collections.Generic.List[PSCustomObject]]::new()
    foreach ($r in $Script:ScanResults) {
        if ($r.Permissions -and $r.Permissions.Count -gt 0) {
            foreach ($p in $r.Permissions) {
                $risk = Get-RiskLevel -Principal $p.Principal -LoginName $p.LoginName `
                    -PermLevel $p.PermLevel -PrincipalType $p.PrincipalType
                $rows.Add([PSCustomObject]@{
                    SiteName             = $r.SiteName
                    SiteUrl              = $r.SiteUrl
                    ObjectType           = $r.ObjectType
                    ObjectName           = $r.ObjectName
                    ObjectUrl            = $r.ObjectUrl
                    HasUniquePermissions = $r.HasUniquePermissions
                    InheritedFrom        = $r.InheritedFrom
                    Principal            = $p.Principal
                    LoginName            = $p.LoginName
                    PrincipalType        = $p.PrincipalType
                    PermissionLevel      = $p.PermLevel
                    Risk                 = $risk
                    ScannedAt            = $r.ScannedAt
                })
            }
        } else {
            $rows.Add([PSCustomObject]@{
                SiteName             = $r.SiteName
                SiteUrl              = $r.SiteUrl
                ObjectType           = $r.ObjectType
                ObjectName           = $r.ObjectName
                ObjectUrl            = $r.ObjectUrl
                HasUniquePermissions = $r.HasUniquePermissions
                InheritedFrom        = $r.InheritedFrom
                Principal            = ""
                LoginName            = ""
                PrincipalType        = ""
                PermissionLevel      = $(if ($r.HasUniquePermissions) { "(no assignments)" } else { "(inherited)" })
                Risk                 = "OK"
                ScannedAt            = $r.ScannedAt
            })
        }
    }
    if ($FocusUser) {
        $rows = [System.Collections.Generic.List[PSCustomObject]]($rows | Where-Object {
            $_.Principal -like "*$FocusUser*" -or $_.LoginName -like "*$FocusUser*"
        })
        Write-Log "FocusUser '$FocusUser' : $($rows.Count) lignes" -Level INFO
    }
    $rows | Export-Csv -Path $CsvPath -Encoding UTF8 -NoTypeInformation -Force
    Write-Log "CSV : $CsvPath ($($rows.Count) lignes)" -Level OK
    return $rows
}

# ── Comparaison ────────────────────────────────────────────────────────────────
function Get-Comparison {
    param([string]$PreviousCsv, [string]$CurrentCsv)
    if (-not (Test-Path $PreviousCsv)) {
        Write-Log "CSV precedent introuvable : $PreviousCsv" -Level WARN
        return $null
    }
    Write-Log "Comparaison avec : $PreviousCsv" -Level INFO
    $prev = Import-Csv $PreviousCsv
    $curr = Import-Csv $CurrentCsv
    $prevKeys = @{}; foreach ($r in $prev) { $prevKeys["$($r.SiteUrl)|$($r.ObjectUrl)|$($r.Principal)|$($r.PermissionLevel)"] = $r }
    $currKeys = @{}; foreach ($r in $curr) { $currKeys["$($r.SiteUrl)|$($r.ObjectUrl)|$($r.Principal)|$($r.PermissionLevel)"] = $r }
    $added   = [System.Collections.Generic.List[PSCustomObject]]::new()
    $removed = [System.Collections.Generic.List[PSCustomObject]]::new()
    foreach ($k in $currKeys.Keys) { if (-not $prevKeys.ContainsKey($k)) { $added.Add($currKeys[$k]) } }
    foreach ($k in $prevKeys.Keys) { if (-not $currKeys.ContainsKey($k)) { $removed.Add($prevKeys[$k]) } }
    Write-Log "Diff : +$($added.Count) / -$($removed.Count)" -Level OK
    return @{ Added = $added; Removed = $removed }
}

# ── Rapport HTML ───────────────────────────────────────────────────────────────
function New-HtmlReport {
    Write-Log "Generating report..." -Level INFO

    $scanDuration = [math]::Round(((Get-Date) - $Script:StartTime).TotalSeconds, 1)
    $genDate      = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $uniqueCount  = @($Script:ScanResults | Where-Object { $_.HasUniquePermissions }).Count
    $siteCount    = @($Script:ScanResults | Where-Object { $_.ObjectType -eq "Site" }).Count
    $errorCount   = $Script:ScanErrors.Count
    $csvPath      = $OutputPath -replace '\.html$', '.csv'
    $csvFileName  = [System.IO.Path]::GetFileName($csvPath)

    # 1. Exporter le CSV
    $rows = Export-CsvReport -CsvPath $csvPath

    # 2. Comparaison diff
    $addedJson   = '[]'
    $removedJson = '[]'
    $hasCompare  = 'false'
    $addedCount  = 0; $removedCount = 0
    if ($CompareWith) {
        $diff = Get-Comparison -PreviousCsv $CompareWith -CurrentCsv $csvPath
        if ($diff) {
            $hasCompare   = 'true'
            $addedCount   = $diff.Added.Count
            $removedCount = $diff.Removed.Count
            if ($addedCount   -gt 0) { $addedJson   = $diff.Added   | ConvertTo-Json -Compress -Depth 2 }
            if ($removedCount -gt 0) { $removedJson = $diff.Removed | ConvertTo-Json -Compress -Depth 2 }
            $diffCsv = $OutputPath -replace '\.html$', '_diff.csv'
            (@($diff.Added) + @($diff.Removed)) | Export-Csv $diffCsv -Encoding UTF8 -NoTypeInformation -Force
        }
    }

    # 3. Trouver le template
    # $PSScriptRoot est vide dans un Start-Job - on essaie plusieurs emplacements
    $templatePath = $null
    $candidates = @(
        (Join-Path $PSScriptRoot         "SPPermissions_template.html"),  # Normal
        (Join-Path (Get-Location).Path   "SPPermissions_template.html"),  # Working dir
        (Join-Path $env:SP_SCANNER_DIR   "SPPermissions_template.html"),  # Via env var (Start-Job)
        (Join-Path (Split-Path $OutputPath -Parent) "SPPermissions_template.html")  # Cote du rapport
    )
    foreach ($c in $candidates) {
        if ($c -and (Test-Path $c)) { $templatePath = $c; break }
    }
    if (-not $templatePath) {
        Write-Log "Template SPPermissions_template.html introuvable." -Level ERROR
        Write-Log "Emplacements essayes : $($candidates -join ', ')" -Level WARN
        Write-Log "Placez SPPermissions_template.html dans le meme dossier que le script." -Level WARN
        return
    }
    Write-Log "Template : $templatePath" -Level INFO

    # 4. Lire le template et injecter les placeholders (remplacements simples et fiables)
    $metaJson = [ordered]@{
        generatedAt = $genDate
        mode        = $Mode
        scanDepth   = $ScanDepth
        duration    = $scanDuration
        errors      = $errorCount
        totalRows   = $rows.Count
    } | ConvertTo-Json -Compress

    $html = [System.IO.File]::ReadAllText($templatePath, [System.Text.Encoding]::UTF8)
    $html = $html.Replace('__CSV_FILENAME__',  $csvFileName)
    $html = $html.Replace('__META_JSON__',     $metaJson)
    $html = $html.Replace('__DIFF_ADDED__',    $addedJson)
    $html = $html.Replace('__DIFF_REMOVED__',  $removedJson)
    $html = $html.Replace('__HAS_COMPARE__',   $hasCompare)

    [System.IO.File]::WriteAllText($OutputPath, $html, [System.Text.Encoding]::UTF8)
    Write-Log "HTML : $OutputPath" -Level OK
    Write-Log "CSV  : $csvPath"    -Level OK
}


#endregion


try {
    # Validate parameters
    if ($Mode -eq "SingleSite" -and -not $SiteUrl)       { throw "SiteUrl is required for SingleSite mode." }
    if ($Mode -eq "SiteCollection" -and -not $SiteUrl)   { throw "SiteUrl is required for SiteCollection mode." }
    if ($Mode -eq "AllSites" -and -not $TenantAdminUrl)  { throw "TenantAdminUrl is required for AllSites mode." }

    # Show auth params for troubleshooting
    Write-Log "Auth params received :" -Level INFO
    Write-Log "  ClientId   = '$ClientId'" -Level INFO
    Write-Log "  Thumbprint = '$Thumbprint'" -Level INFO
    Write-Log "  Tenant     = '$Tenant'" -Level INFO

    # Check certificate in store if thumbprint provided
    if ($Thumbprint) {
        $certUser    = Get-Item "Cert:\CurrentUser\My\$Thumbprint"  -ErrorAction SilentlyContinue
        $certMachine = Get-Item "Cert:\LocalMachine\My\$Thumbprint" -ErrorAction SilentlyContinue
        if ($certUser)    { Write-Log "Certificate found in CurrentUser\My store." -Level OK }
        elseif ($certMachine) { Write-Log "Certificate found in LocalMachine\My store." -Level OK }
        else {
            Write-Log "Certificate NOT found in any store! Thumbprint: $Thumbprint" -Level WARN
            Write-Log "Run: Import-PfxCertificate -FilePath '<path>.pfx' -CertStoreLocation Cert:\CurrentUser\My" -Level WARN
        }
    }

    # Check PnP module
    # Verifier PnP.PowerShell
    if (-not (Get-Module -ListAvailable -Name "PnP.PowerShell")) {
        Write-Log "PnP.PowerShell non installe. Lancez : Install-Module PnP.PowerShell -Scope CurrentUser" -Level ERROR
        exit 1
    }
    # Importer PnP proprement en evitant les conflits d assemblies Microsoft.Graph
    # Si Microsoft.Graph SDK est deja charge dans la session, PnP peut entrer en conflit.
    # Solution : ne pas importer explicitement (PnP.PowerShell s auto-importe via ses cmdlets)
    # et ignorer les erreurs d assembly non critiques.
    if (-not (Get-Module -Name "PnP.PowerShell")) {
        try {
            Import-Module PnP.PowerShell -ErrorAction Stop -WarningAction SilentlyContinue
            Write-Log "PnP.PowerShell charge." -Level OK
        } catch {
            if ($_.Exception.Message -like "*Assembly*already loaded*" -or
                $_.Exception.Message -like "*Could not load file or assembly*") {
                Write-Log "Avertissement assembly Graph (non bloquant) - le script continue." -Level WARN
            } else {
                Write-Log "Erreur chargement PnP.PowerShell : $_" -Level ERROR
                Write-Log "Conseil : Ouvrez une nouvelle session PowerShell et relancez le script." -Level WARN
                exit 1
            }
        }
    }

    # Choix interactif du ScanDepth si pas specifie (valeur par defaut)
    if (-not $PSBoundParameters.ContainsKey('ScanDepth')) {
        Write-Host ""
        Write-Host "  Profondeur de scan :" -ForegroundColor Cyan
        Write-Host "  [1] Site uniquement                          (tres rapide)" -ForegroundColor White
        Write-Host "  [2] Site + Bibliotheques/Listes              (rapide - recommande)" -ForegroundColor White
        Write-Host "  [3] Site + Bibliotheques + Dossiers/Fichiers (lent)" -ForegroundColor White
        Write-Host ""
        Write-Host "  Votre choix [1/2/3] (defaut: 2) : " -NoNewline -ForegroundColor Yellow
        $choice = Read-Host
        $ScanDepth = switch ($choice) {
            "1" { "Site" }
            "3" { "Full" }
            default { "SiteAndLibraries" }
        }
        Write-Log "ScanDepth selectionne : $ScanDepth" -Level OK
    }

    # Orchestration du scan
    Write-Log "═══════════════════════════════════════════════" -Level SECTION
    Write-Log "  SharePoint Permission Scanner  v1.0" -Level SECTION
    Write-Log "  Mode      : $Mode" -Level SECTION
    Write-Log "  ScanDepth : $ScanDepth" -Level SECTION
    Write-Log "═══════════════════════════════════════════════" -Level SECTION

    switch ($Mode) {
        "SingleSite" {
            Invoke-ScanSite -Url $SiteUrl
        }
        "SiteCollection" {
            Connect-ToSite -Url $SiteUrl
            $subsiteUrls = @(Get-PnPSubWeb -Recurse | Select-Object -ExpandProperty Url)
            Disconnect-PnPOnline
            Invoke-ScanSite -Url $SiteUrl
            foreach ($subUrl in $subsiteUrls) { Invoke-ScanSite -Url $subUrl }
        }
        "AllSites" {
            if (-not $TenantAdminUrl) { throw "TenantAdminUrl is required for AllSites mode." }
            Connect-ToSite -Url $TenantAdminUrl
            $allSites = Get-PnPTenantSite -IncludeOneDriveSites:$false | Select-Object -ExpandProperty Url
            Disconnect-PnPOnline
            Write-Log "Found $($allSites.Count) sites to scan." -Level OK
            foreach ($siteUrl in $allSites) { Invoke-ScanSite -Url $siteUrl }
        }
    }

    Write-Log "Scan complete. Total objects scanned: $Script:TotalScanned" -Level OK
    New-HtmlReport

    Write-Log "═══════════════════════════════════" -Level SECTION
    Write-Log "  Done! Report: $OutputPath" -Level OK
    Write-Log "═══════════════════════════════════" -Level SECTION


    # Ouvrir le rapport - uniquement en mode interactif
    # En mode non-interactif (Start-SPScanner.ps1), on saute cette etape
    if ([Environment]::UserInteractive -and -not ([Console]::IsInputRedirected)) {
        try {
            $openReport = Read-Host "Open report in browser? (Y/N)"
            if ($openReport -eq "Y") {
                $absPath = (Resolve-Path $OutputPath -ErrorAction SilentlyContinue | Select-Object -ExpandProperty Path -ErrorAction SilentlyContinue)
                if (-not $absPath) { $absPath = $OutputPath }
                Start-Process "explorer.exe" -ArgumentList "`"$absPath`""
            }
        } catch { }
    }

} catch {
    Write-Log "Fatal error: $_" -Level ERROR
    Write-Log $_.ScriptStackTrace -Level ERROR
    exit 1
}

#endregion