#Requires -Modules PnP.PowerShell
<#
.SYNOPSIS
    SharePoint Permission Scanner - Generates a detailed HTML report of all permissions
    across SharePoint sites, libraries, folders, and files.

.DESCRIPTION
    This script connects to SharePoint Online using PnP PowerShell and recursively
    scans permissions at all levels: Site, Lists/Libraries, Folders, and Files.
    It detects broken inheritance and exports a rich interactive HTML report.

.PARAMETER Mode
    Scanning mode:
      - SingleSite     : Scan a single SharePoint site
      - AllSites       : Scan all sites in the tenant
      - SiteCollection : Scan a specific site collection (root + subsites)

.PARAMETER SiteUrl
    URL of the SharePoint site (required for SingleSite and SiteCollection modes).

.PARAMETER TenantAdminUrl
    URL of the SharePoint Admin Center (e.g. https://contoso-admin.sharepoint.com).
    Required for AllSites mode.

.PARAMETER OutputPath
    Path and filename for the HTML report. Defaults to .\SPPermissions_<timestamp>.html

.PARAMETER IncludeFiles
    If set, scans individual file permissions (slower but more thorough). Default: $true

.PARAMETER MaxFileDepth
    Maximum folder depth to scan for files. Default: 10

.PARAMETER ExcludeSystemLists
    Exclude SharePoint system lists (Style Library, Site Assets, etc.). Default: $true

.PARAMETER ClientId
    Azure AD App Registration Client ID for app-only authentication.

.PARAMETER Thumbprint
    Certificate thumbprint for app-only authentication.

.PARAMETER Tenant
    Tenant ID or domain for app-only authentication.

.EXAMPLE
    # Interactive login - Single site
    .\SPPermissionScanner.ps1 -Mode SingleSite -SiteUrl "https://contoso.sharepoint.com/sites/HR"

.EXAMPLE
    # All sites in tenant
    .\SPPermissionScanner.ps1 -Mode AllSites -TenantAdminUrl "https://contoso-admin.sharepoint.com"

.EXAMPLE
    # App-only auth - Site collection
    .\SPPermissionScanner.ps1 -Mode SiteCollection -SiteUrl "https://contoso.sharepoint.com/sites/Projects" `
        -ClientId "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" `
        -Thumbprint "ABCDEF1234567890" `
        -Tenant "contoso.onmicrosoft.com"

.NOTES
    Author  : Generated by Claude
    Version : 1.0
    Requires: PnP.PowerShell module (Install-Module PnP.PowerShell)
    
    Required permissions (App-only):
      - Sites.FullControl.All (SharePoint)
      - Directory.Read.All (Graph - for user/group details)
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [ValidateSet("SingleSite", "AllSites", "SiteCollection")]
    [string]$Mode,

    [Parameter()]
    [string]$SiteUrl,

    [Parameter()]
    [string]$TenantAdminUrl,

    [Parameter()]
    [string]$OutputPath = ".\SPPermissions_$(Get-Date -Format 'yyyyMMdd_HHmmss').html",

    [Parameter()]
    [ValidateSet("Site", "SiteAndLibraries", "Full")]
    [string]$ScanDepth = "SiteAndLibraries",
    # Site              : Site uniquement (permissions du site)
    # SiteAndLibraries  : Site + Listes/Bibliotheques (recommande, rapide)
    # Full              : Site + Bibliotheques + Dossiers + Fichiers (lent)

    [Parameter()]
    [bool]$ExcludeSystemLists = $true,

    [Parameter()]
    [string]$ClientId,

    [Parameter()]
    [string]$Thumbprint,

    [Parameter()]
    [string]$Tenant
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

#region ──────────────────────── GLOBALS ────────────────────────

$Script:ScanResults   = [System.Collections.Generic.List[PSCustomObject]]::new()
$Script:ScanErrors    = [System.Collections.Generic.List[PSCustomObject]]::new()
$Script:TotalScanned  = 0
$Script:StartTime     = Get-Date
$Script:SystemLists   = @(
    "appdata", "appfiles", "composed looks", "converted forms",
    "form templates", "list template gallery", "master page gallery",
    "preservation hold library", "site collection images",
    "site pages", "solution gallery", "style library",
    "theme gallery", "user information list", "web part gallery",
    "site assets", "cache profiles", "content and structure reports",
    "content type publishing error log", "customized reports",
    "designated sites", "devices", "hold reports", "relationships list",
    "reusable content", "suggested content browser locations",
    "taxonomy hidden list", "translation status", "wfpub", "wfsvc"
)

#endregion

#region ──────────────────────── HELPERS ────────────────────────

function Write-Log {
    param([string]$Message, [string]$Level = "INFO")
    $timestamp = Get-Date -Format "HH:mm:ss"
    $color = switch ($Level) {
        "INFO"    { "Cyan" }
        "OK"      { "Green" }
        "WARN"    { "Yellow" }
        "ERROR"   { "Red" }
        "SECTION" { "Magenta" }
        default   { "White" }
    }
    Write-Host "[$timestamp] " -NoNewline -ForegroundColor DarkGray
    Write-Host "[$Level] " -NoNewline -ForegroundColor $color
    Write-Host $Message
}

function Add-Result {
    param(
        [string]$SiteUrl,
        [string]$SiteName,
        [string]$ObjectType,   # Site | Library | List | Folder | File
        [string]$ObjectName,
        [string]$ObjectUrl,
        [bool]$HasUniquePermissions,
        [string]$InheritedFrom,
        [PSCustomObject[]]$Permissions
    )
    $Script:ScanResults.Add([PSCustomObject]@{
        SiteUrl              = $SiteUrl
        SiteName             = $SiteName
        ObjectType           = $ObjectType
        ObjectName           = $ObjectName
        ObjectUrl            = $ObjectUrl
        HasUniquePermissions = $HasUniquePermissions
        InheritedFrom        = $InheritedFrom
        Permissions          = $Permissions
        ScannedAt            = (Get-Date -Format "o")
    })
    $Script:TotalScanned++
}



#endregion

#region ──────────────────────── CONNECT ────────────────────────

function Connect-ToSite {
    param([string]$Url)
    Write-Log "Connecting to: $Url" -Level INFO
    try {
        if ($ClientId -and $Thumbprint -and $Tenant) {
            # Verify certificate exists in store
            $cert = Get-Item "Cert:\CurrentUser\My\$Thumbprint" -ErrorAction SilentlyContinue
            if (-not $cert) {
                $cert = Get-Item "Cert:\LocalMachine\My\$Thumbprint" -ErrorAction SilentlyContinue
            }
            if (-not $cert) {
                throw "Certificate with thumbprint '$Thumbprint' not found in CurrentUser\My or LocalMachine\My store. Import the .pfx file first: Import-PfxCertificate -FilePath '<path>.pfx' -CertStoreLocation Cert:\CurrentUser\My"
            }
            Write-Log "Certificate found: $($cert.Subject) (expires $($cert.NotAfter.ToString('yyyy-MM-dd')))" -Level OK
            # App-only auth with certificate thumbprint
            Connect-PnPOnline -Url $Url `
                -ClientId $ClientId `
                -Thumbprint $Thumbprint `
                -Tenant $Tenant `
                -ErrorAction Stop
        } elseif ($ClientId -and $Tenant) {
            # App-only auth - interactive device login
            Connect-PnPOnline -Url $Url `
                -ClientId $ClientId `
                -Tenant $Tenant `
                -Interactive `
                -ErrorAction Stop
        } else {
            # Delegated interactive login (uses PnP community app)
            Connect-PnPOnline -Url $Url -Interactive -ErrorAction Stop
        }
        Write-Log "Connected successfully." -Level OK
    } catch {
        Write-Log "Connection failed: $_" -Level ERROR
        throw
    }
}

#endregion

#region ──────────────────────── SCAN FUNCTIONS ────────────────────────

function Invoke-ScanItem {
    param(
        [string]$SiteUrl,
        [string]$SiteName,
        [string]$ListTitle,
        [object]$Item,
        [string]$ParentName,
        [string]$ObjectType
    )
    try {
        $hasUnique = $Item.HasUniqueRoleAssignments
        # Charger toujours les permissions effectives (heritees ou uniques)
        $perms = Get-SPPermissions -SecurableObject $Item
        $name = if ($Item.FieldValues["FileLeafRef"]) { $Item.FieldValues["FileLeafRef"] } else { $Item.FieldValues["Title"] }
        $ref  = $Item.FieldValues["FileRef"]
        $url  = if ($ref) { "$SiteUrl$ref" } else { $SiteUrl }

        Add-Result -SiteUrl $SiteUrl -SiteName $SiteName `
            -ObjectType $ObjectType -ObjectName $name `
            -ObjectUrl $url `
            -HasUniquePermissions $hasUnique `
            -InheritedFrom $(if ($hasUnique) { "" } else { $ParentName }) `
            -Permissions $perms

        $icon = if ($ObjectType -eq "Folder") { "F" } else { "D" }
        Write-Log "  [$icon] $ObjectType : $name | Unique: $hasUnique" -Level INFO
    } catch {
        $Script:ScanErrors.Add([PSCustomObject]@{ Item = "$ListTitle/$($Item.Id)"; Error = $_.ToString() })
        Write-Log "  Error scanning $ObjectType $($Item.Id): $_" -Level WARN
    }
}

function Invoke-ScanList {
    param(
        [string]$SiteUrl,
        [string]$SiteName,
        [object]$List
    )
    $listType = if ($List.BaseType -eq "DocumentLibrary") { "Library" } else { "List" }
    Write-Log "  📚 Scanning $listType : $($List.Title)" -Level INFO

    try {
        # Permissions de la liste/bibliotheque (toujours chargees, heritees ou uniques)
        $listFull  = Get-PnPList -Identity $List.Id -Includes HasUniqueRoleAssignments, RoleAssignments
        $hasUnique = $listFull.HasUniqueRoleAssignments

        # On charge toujours les permissions effectives (meme si heritees du site)
        $perms = Get-SPPermissions -SecurableObject $listFull

        Add-Result -SiteUrl $SiteUrl -SiteName $SiteName `
            -ObjectType $listType -ObjectName $List.Title `
            -ObjectUrl "$SiteUrl$($List.DefaultViewUrl)" `
            -HasUniquePermissions $hasUnique `
            -InheritedFrom $(if ($hasUnique) { "" } else { $SiteName }) `
            -Permissions $perms

        # Scanner les items selon le ScanDepth
        if ($ScanDepth -eq "Full" -and $List.BaseType -eq "DocumentLibrary") {
            $items = Get-PnPListItem -List $List.Id `
                -Fields "FileLeafRef","FileRef","FSObjType" `
                -Includes HasUniqueRoleAssignments `
                -PageSize 500
            Write-Log "    $($items.Count) items dans $($List.Title)" -Level INFO
            foreach ($item in $items) {
                $fsoType  = $item.FieldValues["FSObjType"]
                $itemType = if ($fsoType -eq 1) { "Folder" } else { "File" }
                Invoke-ScanItem -SiteUrl $SiteUrl -SiteName $SiteName `
                    -ListTitle $List.Title -Item $item `
                    -ParentName $List.Title -ObjectType $itemType
            }
        }
    } catch {
        $Script:ScanErrors.Add([PSCustomObject]@{ Item = $List.Title; Error = $_.ToString() })
        Write-Log "  Error scanning list $($List.Title): $_" -Level WARN
    }
}

function Get-SPPermissions {
    # Extrait les permissions d un objet SharePoint via Get-PnPProperty (charge les sous-objets)
    param([object]$SecurableObject)
    $perms = @()
    try {
        Get-PnPProperty -ClientObject $SecurableObject -Property HasUniqueRoleAssignments, RoleAssignments | Out-Null
        foreach ($ra in $SecurableObject.RoleAssignments) {
            Get-PnPProperty -ClientObject $ra -Property Member, RoleDefinitionBindings | Out-Null
            $levels = ($ra.RoleDefinitionBindings | Select-Object -ExpandProperty Name) -join ", "
            $type = switch -Wildcard ($ra.Member.PrincipalType.ToString()) {
                "User"            { "User" }
                "SharePointGroup" { "SP Group" }
                "SecurityGroup"   { "Security Group" }
                default           { $ra.Member.PrincipalType.ToString() }
            }
            $perms += [PSCustomObject]@{
                Principal     = $ra.Member.Title
                LoginName     = $ra.Member.LoginName
                PrincipalType = $type
                PermLevel     = $levels
            }
        }
    } catch {
        Write-Log "Could not load permissions: $_" -Level WARN
    }
    return $perms
}

function Invoke-ScanSite {
    param([string]$Url)
    Write-Log "─── Scanning site: $Url" -Level SECTION

    try {
        Connect-ToSite -Url $Url

        $web = Get-PnPWeb -Includes Title, HasUniqueRoleAssignments, RoleAssignments, Url
        $siteName = $web.Title
        Write-Log "Site: $siteName" -Level OK

        $sitePerms = Get-SPPermissions -SecurableObject $web

        Add-Result -SiteUrl $Url -SiteName $siteName `
            -ObjectType "Site" -ObjectName $siteName `
            -ObjectUrl $Url `
            -HasUniquePermissions $true `
            -InheritedFrom "" `
            -Permissions $sitePerms

        # Listes et bibliotheques (sauf si ScanDepth = Site)
        if ($ScanDepth -ne "Site") {
            $lists = Get-PnPList -Includes BaseType, HasUniqueRoleAssignments, DefaultViewUrl, Hidden, Id
            foreach ($list in $lists) {
                if ($list.Hidden) { continue }
                if ($ExcludeSystemLists -and ($Script:SystemLists -contains $list.Title.ToLower())) { continue }
                Invoke-ScanList -SiteUrl $Url -SiteName $siteName -List $list
            }
        } else {
            Write-Log "  ScanDepth=Site : listes/bibliotheques ignorees." -Level INFO
        }

        Disconnect-PnPOnline
    } catch {
        $Script:ScanErrors.Add([PSCustomObject]@{ Item = $Url; Error = $_.ToString() })
        Write-Log "Failed to scan site $Url : $_" -Level ERROR
        try { Disconnect-PnPOnline -ErrorAction SilentlyContinue } catch {}
    }
}
#endregion

#region ── REPORT ──

function Export-CsvReport {
    param([string]$CsvPath)
    $rows = [System.Collections.Generic.List[PSCustomObject]]::new()
    foreach ($r in $Script:ScanResults) {
        if ($r.Permissions -and $r.Permissions.Count -gt 0) {
            foreach ($p in $r.Permissions) {
                $rows.Add([PSCustomObject]@{
                    SiteName             = $r.SiteName
                    SiteUrl              = $r.SiteUrl
                    ObjectType           = $r.ObjectType
                    ObjectName           = $r.ObjectName
                    ObjectUrl            = $r.ObjectUrl
                    HasUniquePermissions = $r.HasUniquePermissions
                    InheritedFrom        = $r.InheritedFrom
                    Principal            = $p.Principal
                    LoginName            = $p.LoginName
                    PrincipalType        = $p.PrincipalType
                    PermissionLevel      = $p.PermLevel
                    ScannedAt            = $r.ScannedAt
                })
            }
        } else {
            $rows.Add([PSCustomObject]@{
                SiteName             = $r.SiteName
                SiteUrl              = $r.SiteUrl
                ObjectType           = $r.ObjectType
                ObjectName           = $r.ObjectName
                ObjectUrl            = $r.ObjectUrl
                HasUniquePermissions = $r.HasUniquePermissions
                InheritedFrom        = $r.InheritedFrom
                Principal            = ''
                LoginName            = ''
                PrincipalType        = ''
                PermissionLevel      = $(if ($r.HasUniquePermissions) { '(no assignments)' } else { '(inherited)' })
                ScannedAt            = $r.ScannedAt
            })
        }
    }
    $rows | Export-Csv -Path $CsvPath -Encoding UTF8 -NoTypeInformation -Force
    Write-Log "CSV exported: $CsvPath ($($rows.Count) rows)" -Level OK
    return $rows
}

function New-HtmlReport {
    Write-Log "Generating report..." -Level INFO

    $scanDuration = [math]::Round(((Get-Date) - $Script:StartTime).TotalSeconds, 1)
    $genDate      = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $uniqueCount  = @($Script:ScanResults | Where-Object { $_.HasUniquePermissions }).Count
    $siteCount    = @($Script:ScanResults | Where-Object { $_.ObjectType -eq "Site" }).Count
    $errorCount   = $Script:ScanErrors.Count
    $csvPath      = $OutputPath -replace '\.html$', '.csv'

    # 1. Ecrire le CSV
    $csvRows = [System.Collections.Generic.List[PSCustomObject]]::new()
    foreach ($r in $Script:ScanResults) {
        if ($r.Permissions -and $r.Permissions.Count -gt 0) {
            foreach ($p in $r.Permissions) {
                $csvRows.Add([PSCustomObject]@{
                    SiteName             = $r.SiteName
                    SiteUrl              = $r.SiteUrl
                    ObjectType           = $r.ObjectType
                    ObjectName           = $r.ObjectName
                    ObjectUrl            = $r.ObjectUrl
                    HasUniquePermissions = $r.HasUniquePermissions
                    InheritedFrom        = $r.InheritedFrom
                    Principal            = $p.Principal
                    LoginName            = $p.LoginName
                    PrincipalType        = $p.PrincipalType
                    PermissionLevel      = $p.PermLevel
                })
            }
        } else {
            $csvRows.Add([PSCustomObject]@{
                SiteName             = $r.SiteName
                SiteUrl              = $r.SiteUrl
                ObjectType           = $r.ObjectType
                ObjectName           = $r.ObjectName
                ObjectUrl            = $r.ObjectUrl
                HasUniquePermissions = $r.HasUniquePermissions
                InheritedFrom        = $r.InheritedFrom
                Principal            = ""
                LoginName            = ""
                PrincipalType        = ""
                PermissionLevel      = $(if ($r.HasUniquePermissions) { "(no assignments)" } else { "(inherited)" })
            })
        }
    }
    $csvRows | Export-Csv -Path $csvPath -Encoding UTF8 -NoTypeInformation -Force
    Write-Log "CSV : $csvPath ($($csvRows.Count) lignes)" -Level OK

    # 2. Relire le CSV - methode eprouvee
    $data = Import-Csv -Path $csvPath

    # 3. CSS - single-quoted, aucune interpolation PS
    $css = @'
<meta charset="UTF-8">
<style>
body{font-family:Segoe UI,Arial,sans-serif;background:#0f1117;color:#e2e8f0;font-size:13px;margin:0}
.hdr{background:linear-gradient(135deg,#0d1525,#0f1117);border-bottom:2px solid #1c2540;padding:14px 20px;display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:10px}
.logo{width:34px;height:34px;background:linear-gradient(135deg,#2563eb,#7c3aed);border-radius:8px;display:inline-flex;align-items:center;justify-content:center;font-weight:800;color:#fff;font-size:14px;margin-right:10px;vertical-align:middle}
.brand{font-size:16px;font-weight:700;color:#e2e8f0}.brand b{color:#60a5fa}
.sub{font-size:10px;color:#4a5568;font-family:Consolas,monospace;margin-top:2px}
.stats{display:flex;gap:4px;flex-wrap:wrap}
.stat{background:#161b27;padding:6px 14px;text-align:center;border:1px solid #1c2540;border-radius:4px}
.sn{font-size:17px;font-weight:700;line-height:1}.sl{font-size:9px;color:#4a5568;text-transform:uppercase;letter-spacing:.07em;margin-top:2px}
.c1{color:#60a5fa}.c2{color:#f59e0b}.c3{color:#ef4444}
.tb{background:#161b27;border-bottom:1px solid #1c2540;padding:8px 14px;display:flex;align-items:center;gap:5px;flex-wrap:wrap;position:sticky;top:0;z-index:100}
.btn{padding:4px 12px;border-radius:4px;border:1px solid #1c2540;background:#1e2535;color:#64748b;cursor:pointer;font-size:11px;font-weight:600;font-family:Segoe UI,sans-serif;transition:all .15s}
.btn:hover,.btn.on{border-color:#3b82f6;color:#60a5fa;background:rgba(59,130,246,.12)}
.bw{border-color:rgba(245,158,11,.4);color:#f59e0b}.bw:hover,.bw.on{background:rgba(245,158,11,.12);border-color:#f59e0b}
.bg{border-color:rgba(16,185,129,.4);color:#10b981}.bg:hover{background:rgba(16,185,129,.1)}
.sp{width:1px;height:18px;background:#1c2540;display:inline-block;vertical-align:middle}
.srch{margin-left:auto;background:#1e2535;border:1px solid #1c2540;border-radius:4px;color:#e2e8f0;padding:5px 10px;font-size:11px;width:200px;outline:none;font-family:Consolas,monospace;transition:border-color .15s,width .2s}
.srch:focus{border-color:#3b82f6;width:260px}
table{width:100%;border-collapse:collapse}
thead{background:#1e2535;position:sticky;top:48px;z-index:10}
th{padding:8px 12px;text-align:left;font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.07em;color:#4a5568;border-bottom:1px solid #1c2540;white-space:nowrap;cursor:pointer}
th:hover{color:#e2e8f0}
td{padding:7px 12px;border-bottom:1px solid rgba(28,37,64,.5);vertical-align:middle}
tr.u td{background:rgba(245,158,11,.025)}tr:hover td{background:rgba(255,255,255,.02)}
.ftr{background:#161b27;border-top:1px solid #1c2540;padding:6px 14px;display:flex;justify-content:space-between;font-family:Consolas,monospace;font-size:10px;color:#4a5568;position:sticky;bottom:0}
.em{display:none;padding:60px;text-align:center;color:#4a5568;font-size:14px}
::-webkit-scrollbar{width:5px;height:5px}::-webkit-scrollbar-thumb{background:#1c2540;border-radius:3px}
</style>
'@

    # 4. PreContent avec interpolation PS
    $totalRows  = $data.Count
    $pre  = "<div class=`"hdr`">"
    $pre += "<div><span class=`"logo`">SP</span><span class=`"brand`">SharePoint <b>Permissions</b></span>"
    $pre += "<div class=`"sub`">$genDate &nbsp;|&nbsp; Mode: $Mode &nbsp;|&nbsp; Depth: $ScanDepth &nbsp;|&nbsp; ${scanDuration}s</div></div>"
    $pre += "<div class=`"stats`">"
    $pre += "<div class=`"stat`"><div class=`"sn c1`">$siteCount</div><div class=`"sl`">Sites</div></div>"
    $pre += "<div class=`"stat`"><div class=`"sn`">$totalRows</div><div class=`"sl`">Lignes</div></div>"
    $pre += "<div class=`"stat`"><div class=`"sn c2`">$uniqueCount</div><div class=`"sl`">Uniques</div></div>"
    $pre += "<div class=`"stat`"><div class=`"sn c3`">$errorCount</div><div class=`"sl`">Erreurs</div></div>"
    $pre += "</div></div>"
    $pre += "<div class=`"tb`">"
    $pre += "<button class=`"btn on`" onclick=`"f('all',this)`">Tous</button>"
    $pre += "<button class=`"btn`" style=`"color:#818cf8;border-color:#818cf8`" onclick=`"f('Site',this)`">Sites</button>"
    $pre += "<button class=`"btn`" style=`"color:#22d3ee;border-color:#22d3ee`" onclick=`"f('Library',this)`">Libraries</button>"
    $pre += "<button class=`"btn`" style=`"color:#fb923c;border-color:#fb923c`" onclick=`"f('List',this)`">Listes</button>"
    $pre += "<button class=`"btn`" style=`"color:#34d399;border-color:#34d399`" onclick=`"f('Folder',this)`">Dossiers</button>"
    $pre += "<button class=`"btn`" style=`"color:#a78bfa;border-color:#a78bfa`" onclick=`"f('File',this)`">Fichiers</button>"
    $pre += "<span class=`"sp`"></span>"
    $pre += "<button class=`"btn bw`" id=`"bu`" onclick=`"uf()`">Uniques seulement</button>"
    $pre += "<span class=`"sp`"></span>"
    $pre += "<button class=`"btn bg`" onclick=`"ex()`">Export CSV</button>"
    $pre += "<input class=`"srch`" id=`"s`" placeholder=`"Rechercher...`" oninput=`"ft()`">"
    $pre += "</div><div class=`"em`" id=`"em`">Aucun resultat.</div>"

    # 5. PostContent - single-quoted here-string = JS pur, zero interpolation PS
    $post = @'
<div class="ftr"><span>SP Permission Scanner v1.0</span><span id="rc"></span></div>
<script>
var tf="all",uo=false;
function init(){
  var trs=document.querySelectorAll("table tbody tr");
  trs.forEach(function(tr){
    var c=tr.querySelectorAll("td");
    if(!c.length)return;
    var ot=c[2]?c[2].textContent.trim():"";
    tr.dataset.t=ot;
    var hu=c[5]?c[5].textContent.trim():"";
    if(hu==="True")tr.className="u";
  });
  cnt();
}
function ft(){
  var q=(document.getElementById("s").value||"").toLowerCase();
  var trs=document.querySelectorAll("table tbody tr");
  var v=0;
  trs.forEach(function(tr){
    var ok=(tf==="all"||tr.dataset.t===tf)&&(!uo||tr.className==="u")&&(!q||tr.textContent.toLowerCase().indexOf(q)!==-1);
    tr.style.display=ok?"":"none";
    if(ok)v++;
  });
  document.getElementById("rc").textContent=v+" lignes";
  document.getElementById("em").style.display=v===0?"block":"none";
}
function cnt(){document.getElementById("rc").textContent=document.querySelectorAll("table tbody tr").length+" lignes";}
function f(t,btn){tf=t;document.querySelectorAll(".tb .btn").forEach(function(b){b.classList.remove("on");});btn.classList.add("on");ft();}
function uf(){uo=!uo;document.getElementById("bu").classList.toggle("on",uo);ft();}
function ex(){
  var rows=[Array.from(document.querySelectorAll("table thead th")).map(function(h){return h.textContent.trim();})];
  document.querySelectorAll("table tbody tr").forEach(function(tr){
    if(tr.style.display==="none")return;
    rows.push(Array.from(tr.querySelectorAll("td")).map(function(c){return '"'+c.textContent.trim().replace(/"/g,'""')+'"';}));
  });
  var a=document.createElement("a");
  a.href=URL.createObjectURL(new Blob(["\uFEFF"+rows.map(function(r){return r.join(",");}).join("\n")],{type:"text/csv;charset=utf-8;"}));
  a.download="sp-export.csv";a.click();
}
window.addEventListener("DOMContentLoaded",init);
</script>
'@

    # 6. Generer via Import-Csv -> ConvertTo-Html -> Out-File (methode eprouvee)
    $data | ConvertTo-Html -Head $css -PreContent $pre -PostContent $post -Title "SP Permissions - $genDate" |
        Out-File -FilePath $OutputPath -Encoding UTF8 -Force

    Write-Log "HTML : $OutputPath" -Level OK
    Write-Log "CSV  : $csvPath"    -Level OK
}



#endregion

#region ──────────────────────── ENTRY POINT ────────────────────────

try {
    # Validate parameters
    if ($Mode -eq "SingleSite" -and -not $SiteUrl)       { throw "SiteUrl is required for SingleSite mode." }
    if ($Mode -eq "SiteCollection" -and -not $SiteUrl)   { throw "SiteUrl is required for SiteCollection mode." }
    if ($Mode -eq "AllSites" -and -not $TenantAdminUrl)  { throw "TenantAdminUrl is required for AllSites mode." }

    # Show auth params for troubleshooting
    Write-Log "Auth params received :" -Level INFO
    Write-Log "  ClientId   = '$ClientId'" -Level INFO
    Write-Log "  Thumbprint = '$Thumbprint'" -Level INFO
    Write-Log "  Tenant     = '$Tenant'" -Level INFO

    # Check certificate in store if thumbprint provided
    if ($Thumbprint) {
        $certUser    = Get-Item "Cert:\CurrentUser\My\$Thumbprint"  -ErrorAction SilentlyContinue
        $certMachine = Get-Item "Cert:\LocalMachine\My\$Thumbprint" -ErrorAction SilentlyContinue
        if ($certUser)    { Write-Log "Certificate found in CurrentUser\My store." -Level OK }
        elseif ($certMachine) { Write-Log "Certificate found in LocalMachine\My store." -Level OK }
        else {
            Write-Log "Certificate NOT found in any store! Thumbprint: $Thumbprint" -Level WARN
            Write-Log "Run: Import-PfxCertificate -FilePath '<path>.pfx' -CertStoreLocation Cert:\CurrentUser\My" -Level WARN
        }
    }

    # Check PnP module
    if (-not (Get-Module -ListAvailable -Name "PnP.PowerShell")) {
        Write-Log "PnP.PowerShell module not found. Install it with: Install-Module PnP.PowerShell" -Level ERROR
        exit 1
    }

    # Choix interactif du ScanDepth si pas specifie (valeur par defaut)
    if (-not $PSBoundParameters.ContainsKey('ScanDepth')) {
        Write-Host ""
        Write-Host "  Profondeur de scan :" -ForegroundColor Cyan
        Write-Host "  [1] Site uniquement                          (tres rapide)" -ForegroundColor White
        Write-Host "  [2] Site + Bibliotheques/Listes              (rapide - recommande)" -ForegroundColor White
        Write-Host "  [3] Site + Bibliotheques + Dossiers/Fichiers (lent)" -ForegroundColor White
        Write-Host ""
        Write-Host "  Votre choix [1/2/3] (defaut: 2) : " -NoNewline -ForegroundColor Yellow
        $choice = Read-Host
        $ScanDepth = switch ($choice) {
            "1" { "Site" }
            "3" { "Full" }
            default { "SiteAndLibraries" }
        }
        Write-Log "ScanDepth selectionne : $ScanDepth" -Level OK
    }

    # Orchestration du scan
    Write-Log "═══════════════════════════════════════════════" -Level SECTION
    Write-Log "  SharePoint Permission Scanner  v1.0" -Level SECTION
    Write-Log "  Mode      : $Mode" -Level SECTION
    Write-Log "  ScanDepth : $ScanDepth" -Level SECTION
    Write-Log "═══════════════════════════════════════════════" -Level SECTION

    switch ($Mode) {
        "SingleSite" {
            Invoke-ScanSite -Url $SiteUrl
        }
        "SiteCollection" {
            Connect-ToSite -Url $SiteUrl
            $subsiteUrls = @(Get-PnPSubWeb -Recurse | Select-Object -ExpandProperty Url)
            Disconnect-PnPOnline
            Invoke-ScanSite -Url $SiteUrl
            foreach ($subUrl in $subsiteUrls) { Invoke-ScanSite -Url $subUrl }
        }
        "AllSites" {
            if (-not $TenantAdminUrl) { throw "TenantAdminUrl is required for AllSites mode." }
            Connect-ToSite -Url $TenantAdminUrl
            $allSites = Get-PnPTenantSite -IncludeOneDriveSites:$false | Select-Object -ExpandProperty Url
            Disconnect-PnPOnline
            Write-Log "Found $($allSites.Count) sites to scan." -Level OK
            foreach ($siteUrl in $allSites) { Invoke-ScanSite -Url $siteUrl }
        }
    }

    Write-Log "Scan complete. Total objects scanned: $Script:TotalScanned" -Level OK
    New-HtmlReport

    Write-Log "═══════════════════════════════════" -Level SECTION
    Write-Log "  Done! Report: $OutputPath" -Level OK
    Write-Log "═══════════════════════════════════" -Level SECTION

    # Open report in browser (optional)
    $openReport = Read-Host "Open report in browser? (Y/N)"
    if ($openReport -eq "Y") {
        $absPath = (Resolve-Path $OutputPath -ErrorAction SilentlyContinue)?.Path
        if (-not $absPath) { $absPath = $OutputPath }
        Write-Log "Opening: $absPath" -Level INFO
        Start-Process "explorer.exe" -ArgumentList "`"$absPath`""
    }

} catch {
    Write-Log "Fatal error: $_" -Level ERROR
    Write-Log $_.ScriptStackTrace -Level ERROR
    exit 1
}

#endregion